"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import clone_client.proto.data_types_pb2
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class NCount(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    N_COUNT_FIELD_NUMBER: builtins.int
    n_count: builtins.int
    def __init__(
        self,
        *,
        n_count: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["n_count", b"n_count"]) -> None: ...

global___NCount = NCount

@typing_extensions.final
class PublishedPressures(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRESSURES_FIELD_NUMBER: builtins.int
    RESPONSE_DATA_FIELD_NUMBER: builtins.int
    @property
    def pressures(self) -> clone_client.proto.data_types_pb2.MusclePressuresState: ...
    @property
    def response_data(self) -> clone_client.proto.data_types_pb2.ServerResponse: ...
    def __init__(
        self,
        *,
        pressures: clone_client.proto.data_types_pb2.MusclePressuresState | None = ...,
        response_data: clone_client.proto.data_types_pb2.ServerResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_pressures", b"_pressures", "pressures", b"pressures", "response_data", b"response_data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_pressures", b"_pressures", "pressures", b"pressures", "response_data", b"response_data"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_pressures", b"_pressures"]) -> typing_extensions.Literal["pressures"] | None: ...

global___PublishedPressures = PublishedPressures

@typing_extensions.final
class PublishedPressuresList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRESSURE_LIST_FIELD_NUMBER: builtins.int
    RESPONSE_DATA_FIELD_NUMBER: builtins.int
    @property
    def pressure_list(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[clone_client.proto.data_types_pb2.MusclePressuresState]: ...
    @property
    def response_data(self) -> clone_client.proto.data_types_pb2.ServerResponse: ...
    def __init__(
        self,
        *,
        pressure_list: collections.abc.Iterable[clone_client.proto.data_types_pb2.MusclePressuresState] | None = ...,
        response_data: clone_client.proto.data_types_pb2.ServerResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["response_data", b"response_data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["pressure_list", b"pressure_list", "response_data", b"response_data"]) -> None: ...

global___PublishedPressuresList = PublishedPressuresList

@typing_extensions.final
class PressureSensorCalibration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MIN_FIELD_NUMBER: builtins.int
    MAX_FIELD_NUMBER: builtins.int
    min: builtins.int
    max: builtins.int
    def __init__(
        self,
        *,
        min: builtins.int = ...,
        max: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["max", b"max", "min", b"min"]) -> None: ...

global___PressureSensorCalibration = PressureSensorCalibration

@typing_extensions.final
class CalibrationData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRESSURE_SENSORS_FIELD_NUMBER: builtins.int
    @property
    def pressure_sensors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PressureSensorCalibration]: ...
    def __init__(
        self,
        *,
        pressure_sensors: collections.abc.Iterable[global___PressureSensorCalibration] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["pressure_sensors", b"pressure_sensors"]) -> None: ...

global___CalibrationData = CalibrationData

@typing_extensions.final
class HandInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class MusclesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    MUSCLES_FIELD_NUMBER: builtins.int
    CALIBRATION_DATA_FIELD_NUMBER: builtins.int
    @property
    def muscles(self) -> google.protobuf.internal.containers.ScalarMap[builtins.int, builtins.str]: ...
    @property
    def calibration_data(self) -> global___CalibrationData: ...
    def __init__(
        self,
        *,
        muscles: collections.abc.Mapping[builtins.int, builtins.str] | None = ...,
        calibration_data: global___CalibrationData | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["calibration_data", b"calibration_data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["calibration_data", b"calibration_data", "muscles", b"muscles"]) -> None: ...

global___HandInfo = HandInfo

@typing_extensions.final
class HandInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INFO_FIELD_NUMBER: builtins.int
    RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def info(self) -> global___HandInfo: ...
    @property
    def response(self) -> clone_client.proto.data_types_pb2.ServerResponse: ...
    def __init__(
        self,
        *,
        info: global___HandInfo | None = ...,
        response: clone_client.proto.data_types_pb2.ServerResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["info", b"info", "response", b"response"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["info", b"info", "response", b"response"]) -> None: ...

global___HandInfoResponse = HandInfoResponse
