# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clone_client/state_store/proto/state_store.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from clone_client.proto import data_types_pb2 as clone__client_dot_proto_dot_data__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0clone_client/state_store/proto/state_store.proto\x12\x13\x63lonepb.state_store\x1a\x1bgoogle/protobuf/empty.proto\x1a#clone_client/proto/data_types.proto\"#\n\x13TrackingDataMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\"\x19\n\x06NCount\x12\x0f\n\x07n_count\x18\x01 \x01(\x05\"\xa0\x01\n\x15PublishedTrackingData\x12?\n\x08tracking\x18\x01 \x01(\x0b\x32(.clonepb.state_store.TrackingDataMessageH\x00\x88\x01\x01\x12\x39\n\rresponse_data\x18\x02 \x01(\x0b\x32\".clonepb.data_types.ServerResponseB\x0b\n\t_tracking\"\x9f\x01\n\x12PublishedPressures\x12@\n\tpressures\x18\x01 \x01(\x0b\x32(.clonepb.data_types.MusclePressuresStateH\x00\x88\x01\x01\x12\x39\n\rresponse_data\x18\x02 \x01(\x0b\x32\".clonepb.data_types.ServerResponseB\x0c\n\n_pressures\"\x94\x01\n\x16PublishedPressuresList\x12?\n\rpressure_list\x18\x01 \x03(\x0b\x32(.clonepb.data_types.MusclePressuresState\x12\x39\n\rresponse_data\x18\x02 \x01(\x0b\x32\".clonepb.data_types.ServerResponse\"w\n\x08HandInfo\x12;\n\x07muscles\x18\x02 \x03(\x0b\x32*.clonepb.state_store.HandInfo.MusclesEntry\x1a.\n\x0cMusclesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"u\n\x10HandInfoResponse\x12+\n\x04info\x18\x01 \x01(\x0b\x32\x1d.clonepb.state_store.HandInfo\x12\x34\n\x08response\x18\x02 \x01(\x0b\x32\".clonepb.data_types.ServerResponse2\xbf\x03\n\x13StateStorePublisher\x12W\n\x12SubscribePressures\x12\x16.google.protobuf.Empty\x1a\'.clonepb.state_store.PublishedPressures0\x01\x12O\n\x0cGetPressures\x12\x16.google.protobuf.Empty\x1a\'.clonepb.state_store.PublishedPressures\x12]\n\x11GetLastNPressures\x12\x1b.clonepb.state_store.NCount\x1a+.clonepb.state_store.PublishedPressuresList\x12L\n\x0bGetHandInfo\x12\x16.google.protobuf.Empty\x1a%.clonepb.state_store.HandInfoResponse\x12Q\n\x0bGetTracking\x12\x16.google.protobuf.Empty\x1a*.clonepb.state_store.PublishedTrackingDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clone_client.state_store.proto.state_store_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HANDINFO_MUSCLESENTRY._options = None
  _HANDINFO_MUSCLESENTRY._serialized_options = b'8\001'
  _globals['_TRACKINGDATAMESSAGE']._serialized_start=139
  _globals['_TRACKINGDATAMESSAGE']._serialized_end=174
  _globals['_NCOUNT']._serialized_start=176
  _globals['_NCOUNT']._serialized_end=201
  _globals['_PUBLISHEDTRACKINGDATA']._serialized_start=204
  _globals['_PUBLISHEDTRACKINGDATA']._serialized_end=364
  _globals['_PUBLISHEDPRESSURES']._serialized_start=367
  _globals['_PUBLISHEDPRESSURES']._serialized_end=526
  _globals['_PUBLISHEDPRESSURESLIST']._serialized_start=529
  _globals['_PUBLISHEDPRESSURESLIST']._serialized_end=677
  _globals['_HANDINFO']._serialized_start=679
  _globals['_HANDINFO']._serialized_end=798
  _globals['_HANDINFO_MUSCLESENTRY']._serialized_start=752
  _globals['_HANDINFO_MUSCLESENTRY']._serialized_end=798
  _globals['_HANDINFORESPONSE']._serialized_start=800
  _globals['_HANDINFORESPONSE']._serialized_end=917
  _globals['_STATESTOREPUBLISHER']._serialized_start=920
  _globals['_STATESTOREPUBLISHER']._serialized_end=1367
# @@protoc_insertion_point(module_scope)
