"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import clone_client.proto.data_types_pb2
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class TrackingDataMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        data: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data"]) -> None: ...

global___TrackingDataMessage = TrackingDataMessage

class NCount(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    N_COUNT_FIELD_NUMBER: builtins.int
    n_count: builtins.int
    def __init__(
        self,
        *,
        n_count: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["n_count", b"n_count"]) -> None: ...

global___NCount = NCount

class PublishedTrackingData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRACKING_FIELD_NUMBER: builtins.int
    RESPONSE_DATA_FIELD_NUMBER: builtins.int
    @property
    def tracking(self) -> global___TrackingDataMessage: ...
    @property
    def response_data(self) -> clone_client.proto.data_types_pb2.ServerResponse: ...
    def __init__(
        self,
        *,
        tracking: global___TrackingDataMessage | None = ...,
        response_data: clone_client.proto.data_types_pb2.ServerResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_tracking", b"_tracking", "response_data", b"response_data", "tracking", b"tracking"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_tracking", b"_tracking", "response_data", b"response_data", "tracking", b"tracking"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_tracking", b"_tracking"]) -> typing_extensions.Literal["tracking"] | None: ...

global___PublishedTrackingData = PublishedTrackingData

class PublishedPressures(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRESSURES_FIELD_NUMBER: builtins.int
    RESPONSE_DATA_FIELD_NUMBER: builtins.int
    @property
    def pressures(self) -> clone_client.proto.data_types_pb2.MusclePressuresState: ...
    @property
    def response_data(self) -> clone_client.proto.data_types_pb2.ServerResponse: ...
    def __init__(
        self,
        *,
        pressures: clone_client.proto.data_types_pb2.MusclePressuresState | None = ...,
        response_data: clone_client.proto.data_types_pb2.ServerResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_pressures", b"_pressures", "pressures", b"pressures", "response_data", b"response_data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_pressures", b"_pressures", "pressures", b"pressures", "response_data", b"response_data"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_pressures", b"_pressures"]) -> typing_extensions.Literal["pressures"] | None: ...

global___PublishedPressures = PublishedPressures

class PublishedPressuresList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRESSURE_LIST_FIELD_NUMBER: builtins.int
    RESPONSE_DATA_FIELD_NUMBER: builtins.int
    @property
    def pressure_list(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[clone_client.proto.data_types_pb2.MusclePressuresState]: ...
    @property
    def response_data(self) -> clone_client.proto.data_types_pb2.ServerResponse: ...
    def __init__(
        self,
        *,
        pressure_list: collections.abc.Iterable[clone_client.proto.data_types_pb2.MusclePressuresState] | None = ...,
        response_data: clone_client.proto.data_types_pb2.ServerResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["response_data", b"response_data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["pressure_list", b"pressure_list", "response_data", b"response_data"]) -> None: ...

global___PublishedPressuresList = PublishedPressuresList

class HandInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class MusclesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    MUSCLES_FIELD_NUMBER: builtins.int
    @property
    def muscles(self) -> google.protobuf.internal.containers.ScalarMap[builtins.int, builtins.str]: ...
    def __init__(
        self,
        *,
        muscles: collections.abc.Mapping[builtins.int, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["muscles", b"muscles"]) -> None: ...

global___HandInfo = HandInfo

class HandInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INFO_FIELD_NUMBER: builtins.int
    RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def info(self) -> global___HandInfo: ...
    @property
    def response(self) -> clone_client.proto.data_types_pb2.ServerResponse: ...
    def __init__(
        self,
        *,
        info: global___HandInfo | None = ...,
        response: clone_client.proto.data_types_pb2.ServerResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["info", b"info", "response", b"response"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["info", b"info", "response", b"response"]) -> None: ...

global___HandInfoResponse = HandInfoResponse
