"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import clone_client.proto.data_types_pb2
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class ControllerRuntimeConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MAX_IMPULSE_DURATION_MS_FIELD_NUMBER: builtins.int
    USE_PUMP_FIELD_NUMBER: builtins.int
    ALLOW_MISSING_NODES_FIELD_NUMBER: builtins.int
    max_impulse_duration_ms: builtins.int
    use_pump: builtins.bool
    allow_missing_nodes: builtins.bool
    def __init__(
        self,
        *,
        max_impulse_duration_ms: builtins.int = ...,
        use_pump: builtins.bool = ...,
        allow_missing_nodes: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["allow_missing_nodes", b"allow_missing_nodes", "max_impulse_duration_ms", b"max_impulse_duration_ms", "use_pump", b"use_pump"]) -> None: ...

global___ControllerRuntimeConfig = ControllerRuntimeConfig

@typing_extensions.final
class ValveListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALVE_LIST_FIELD_NUMBER: builtins.int
    RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def valve_list(self) -> clone_client.proto.data_types_pb2.MusclesValveInfo: ...
    @property
    def response(self) -> clone_client.proto.data_types_pb2.ServerResponse: ...
    def __init__(
        self,
        *,
        valve_list: clone_client.proto.data_types_pb2.MusclesValveInfo | None = ...,
        response: clone_client.proto.data_types_pb2.ServerResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["response", b"response", "valve_list", b"valve_list"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["response", b"response", "valve_list", b"valve_list"]) -> None: ...

global___ValveListResponse = ValveListResponse

@typing_extensions.final
class WaterPumpInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DESIRED_PRESSURE_FIELD_NUMBER: builtins.int
    PRESSURE_FIELD_NUMBER: builtins.int
    IS_RUNNING_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    TEMPERATURE_FIELD_NUMBER: builtins.int
    desired_pressure: builtins.float
    pressure: builtins.float
    is_running: builtins.bool
    is_active: builtins.bool
    temperature: builtins.float
    def __init__(
        self,
        *,
        desired_pressure: builtins.float = ...,
        pressure: builtins.float = ...,
        is_running: builtins.bool = ...,
        is_active: builtins.bool = ...,
        temperature: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["desired_pressure", b"desired_pressure", "is_active", b"is_active", "is_running", b"is_running", "pressure", b"pressure", "temperature", b"temperature"]) -> None: ...

global___WaterPumpInfo = WaterPumpInfo

@typing_extensions.final
class WaterPumpInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INFO_FIELD_NUMBER: builtins.int
    RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def info(self) -> global___WaterPumpInfo: ...
    @property
    def response(self) -> clone_client.proto.data_types_pb2.ServerResponse: ...
    def __init__(
        self,
        *,
        info: global___WaterPumpInfo | None = ...,
        response: clone_client.proto.data_types_pb2.ServerResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["info", b"info", "response", b"response"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["info", b"info", "response", b"response"]) -> None: ...

global___WaterPumpInfoResponse = WaterPumpInfoResponse
