# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from clone_client.controller.proto import controller_pb2 as clone__client_dot_controller_dot_proto_dot_controller__pb2
from clone_client.proto import data_types_pb2 as clone__client_dot_proto_dot_data__types__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ControllerGRPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWaterPumpInfo = channel.unary_unary(
                '/clone.controller.ControllerGRPC/GetWaterPumpInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=clone__client_dot_controller_dot_proto_dot_controller__pb2.WaterPumpInfoResponse.FromString,
                )
        self.StartWaterPump = channel.unary_unary(
                '/clone.controller.ControllerGRPC/StartWaterPump',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
                )
        self.StopWaterPump = channel.unary_unary(
                '/clone.controller.ControllerGRPC/StopWaterPump',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
                )
        self.SetWaterPumpPressure = channel.unary_unary(
                '/clone.controller.ControllerGRPC/SetWaterPumpPressure',
                request_serializer=clone__client_dot_proto_dot_data__types__pb2.WaterPumpPressure.SerializeToString,
                response_deserializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
                )
        self.SetMuscles = channel.unary_unary(
                '/clone.controller.ControllerGRPC/SetMuscles',
                request_serializer=clone__client_dot_proto_dot_data__types__pb2.MuscleMovement.SerializeToString,
                response_deserializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
                )
        self.SetPulses = channel.unary_unary(
                '/clone.controller.ControllerGRPC/SetPulses',
                request_serializer=clone__client_dot_proto_dot_data__types__pb2.MusclePulse.SerializeToString,
                response_deserializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
                )
        self.LooseMuscles = channel.unary_unary(
                '/clone.controller.ControllerGRPC/LooseMuscles',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
                )
        self.LockMuscles = channel.unary_unary(
                '/clone.controller.ControllerGRPC/LockMuscles',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
                )
        self.SetPressures = channel.unary_unary(
                '/clone.controller.ControllerGRPC/SetPressures',
                request_serializer=clone__client_dot_proto_dot_data__types__pb2.MusclePressureSetting.SerializeToString,
                response_deserializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
                )
        self.GetValves = channel.unary_unary(
                '/clone.controller.ControllerGRPC/GetValves',
                request_serializer=clone__client_dot_proto_dot_data__types__pb2.GetNodesRequest.SerializeToString,
                response_deserializer=clone__client_dot_controller_dot_proto_dot_controller__pb2.ValveListResponse.FromString,
                )
        self.GetConfig = channel.unary_unary(
                '/clone.controller.ControllerGRPC/GetConfig',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=clone__client_dot_controller_dot_proto_dot_controller__pb2.ControllerRuntimeConfig.FromString,
                )


class ControllerGRPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetWaterPumpInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartWaterPump(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopWaterPump(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWaterPumpPressure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMuscles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPulses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LooseMuscles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LockMuscles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPressures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValves(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerGRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWaterPumpInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWaterPumpInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=clone__client_dot_controller_dot_proto_dot_controller__pb2.WaterPumpInfoResponse.SerializeToString,
            ),
            'StartWaterPump': grpc.unary_unary_rpc_method_handler(
                    servicer.StartWaterPump,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.SerializeToString,
            ),
            'StopWaterPump': grpc.unary_unary_rpc_method_handler(
                    servicer.StopWaterPump,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.SerializeToString,
            ),
            'SetWaterPumpPressure': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWaterPumpPressure,
                    request_deserializer=clone__client_dot_proto_dot_data__types__pb2.WaterPumpPressure.FromString,
                    response_serializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.SerializeToString,
            ),
            'SetMuscles': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMuscles,
                    request_deserializer=clone__client_dot_proto_dot_data__types__pb2.MuscleMovement.FromString,
                    response_serializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.SerializeToString,
            ),
            'SetPulses': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPulses,
                    request_deserializer=clone__client_dot_proto_dot_data__types__pb2.MusclePulse.FromString,
                    response_serializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.SerializeToString,
            ),
            'LooseMuscles': grpc.unary_unary_rpc_method_handler(
                    servicer.LooseMuscles,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.SerializeToString,
            ),
            'LockMuscles': grpc.unary_unary_rpc_method_handler(
                    servicer.LockMuscles,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.SerializeToString,
            ),
            'SetPressures': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPressures,
                    request_deserializer=clone__client_dot_proto_dot_data__types__pb2.MusclePressureSetting.FromString,
                    response_serializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.SerializeToString,
            ),
            'GetValves': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValves,
                    request_deserializer=clone__client_dot_proto_dot_data__types__pb2.GetNodesRequest.FromString,
                    response_serializer=clone__client_dot_controller_dot_proto_dot_controller__pb2.ValveListResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=clone__client_dot_controller_dot_proto_dot_controller__pb2.ControllerRuntimeConfig.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clone.controller.ControllerGRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ControllerGRPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetWaterPumpInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clone.controller.ControllerGRPC/GetWaterPumpInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            clone__client_dot_controller_dot_proto_dot_controller__pb2.WaterPumpInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartWaterPump(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clone.controller.ControllerGRPC/StartWaterPump',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopWaterPump(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clone.controller.ControllerGRPC/StopWaterPump',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetWaterPumpPressure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clone.controller.ControllerGRPC/SetWaterPumpPressure',
            clone__client_dot_proto_dot_data__types__pb2.WaterPumpPressure.SerializeToString,
            clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetMuscles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clone.controller.ControllerGRPC/SetMuscles',
            clone__client_dot_proto_dot_data__types__pb2.MuscleMovement.SerializeToString,
            clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPulses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clone.controller.ControllerGRPC/SetPulses',
            clone__client_dot_proto_dot_data__types__pb2.MusclePulse.SerializeToString,
            clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LooseMuscles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clone.controller.ControllerGRPC/LooseMuscles',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LockMuscles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clone.controller.ControllerGRPC/LockMuscles',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPressures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clone.controller.ControllerGRPC/SetPressures',
            clone__client_dot_proto_dot_data__types__pb2.MusclePressureSetting.SerializeToString,
            clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetValves(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clone.controller.ControllerGRPC/GetValves',
            clone__client_dot_proto_dot_data__types__pb2.GetNodesRequest.SerializeToString,
            clone__client_dot_controller_dot_proto_dot_controller__pb2.ValveListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clone.controller.ControllerGRPC/GetConfig',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            clone__client_dot_controller_dot_proto_dot_controller__pb2.ControllerRuntimeConfig.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
