# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from clone_client.controller.proto import supervisor_pb2 as clone__client_dot_controller_dot_proto_dot_supervisor__pb2
from clone_client.proto import data_types_pb2 as clone__client_dot_proto_dot_data__types__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class SupervisorGRPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCompressorInfo = channel.unary_unary(
                '/clone.controller.SupervisorGRPC/GetCompressorInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=clone__client_dot_controller_dot_proto_dot_supervisor__pb2.CompressorInfoResponse.FromString,
                )
        self.StartCompressor = channel.unary_unary(
                '/clone.controller.SupervisorGRPC/StartCompressor',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
                )
        self.StopCompressor = channel.unary_unary(
                '/clone.controller.SupervisorGRPC/StopCompressor',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
                )
        self.SetCompressorPressure = channel.unary_unary(
                '/clone.controller.SupervisorGRPC/SetCompressorPressure',
                request_serializer=clone__client_dot_proto_dot_data__types__pb2.CompressorPressure.SerializeToString,
                response_deserializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
                )
        self.SetMuscles = channel.unary_unary(
                '/clone.controller.SupervisorGRPC/SetMuscles',
                request_serializer=clone__client_dot_proto_dot_data__types__pb2.MuscleMovement.SerializeToString,
                response_deserializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
                )
        self.LooseMuscles = channel.unary_unary(
                '/clone.controller.SupervisorGRPC/LooseMuscles',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
                )
        self.LockMuscles = channel.unary_unary(
                '/clone.controller.SupervisorGRPC/LockMuscles',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
                )
        self.SetPressures = channel.unary_unary(
                '/clone.controller.SupervisorGRPC/SetPressures',
                request_serializer=clone__client_dot_proto_dot_data__types__pb2.MusclePressureSetting.SerializeToString,
                response_deserializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
                )
        self.GetValves = channel.unary_unary(
                '/clone.controller.SupervisorGRPC/GetValves',
                request_serializer=clone__client_dot_proto_dot_data__types__pb2.GetNodesRequest.SerializeToString,
                response_deserializer=clone__client_dot_controller_dot_proto_dot_supervisor__pb2.ValveListResponse.FromString,
                )


class SupervisorGRPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCompressorInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartCompressor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopCompressor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCompressorPressure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMuscles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LooseMuscles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LockMuscles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPressures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValves(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SupervisorGRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCompressorInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCompressorInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=clone__client_dot_controller_dot_proto_dot_supervisor__pb2.CompressorInfoResponse.SerializeToString,
            ),
            'StartCompressor': grpc.unary_unary_rpc_method_handler(
                    servicer.StartCompressor,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.SerializeToString,
            ),
            'StopCompressor': grpc.unary_unary_rpc_method_handler(
                    servicer.StopCompressor,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.SerializeToString,
            ),
            'SetCompressorPressure': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCompressorPressure,
                    request_deserializer=clone__client_dot_proto_dot_data__types__pb2.CompressorPressure.FromString,
                    response_serializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.SerializeToString,
            ),
            'SetMuscles': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMuscles,
                    request_deserializer=clone__client_dot_proto_dot_data__types__pb2.MuscleMovement.FromString,
                    response_serializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.SerializeToString,
            ),
            'LooseMuscles': grpc.unary_unary_rpc_method_handler(
                    servicer.LooseMuscles,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.SerializeToString,
            ),
            'LockMuscles': grpc.unary_unary_rpc_method_handler(
                    servicer.LockMuscles,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.SerializeToString,
            ),
            'SetPressures': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPressures,
                    request_deserializer=clone__client_dot_proto_dot_data__types__pb2.MusclePressureSetting.FromString,
                    response_serializer=clone__client_dot_proto_dot_data__types__pb2.ServerResponse.SerializeToString,
            ),
            'GetValves': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValves,
                    request_deserializer=clone__client_dot_proto_dot_data__types__pb2.GetNodesRequest.FromString,
                    response_serializer=clone__client_dot_controller_dot_proto_dot_supervisor__pb2.ValveListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clone.controller.SupervisorGRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SupervisorGRPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCompressorInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clone.controller.SupervisorGRPC/GetCompressorInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            clone__client_dot_controller_dot_proto_dot_supervisor__pb2.CompressorInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartCompressor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clone.controller.SupervisorGRPC/StartCompressor',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopCompressor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clone.controller.SupervisorGRPC/StopCompressor',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetCompressorPressure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clone.controller.SupervisorGRPC/SetCompressorPressure',
            clone__client_dot_proto_dot_data__types__pb2.CompressorPressure.SerializeToString,
            clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetMuscles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clone.controller.SupervisorGRPC/SetMuscles',
            clone__client_dot_proto_dot_data__types__pb2.MuscleMovement.SerializeToString,
            clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LooseMuscles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clone.controller.SupervisorGRPC/LooseMuscles',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LockMuscles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clone.controller.SupervisorGRPC/LockMuscles',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPressures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clone.controller.SupervisorGRPC/SetPressures',
            clone__client_dot_proto_dot_data__types__pb2.MusclePressureSetting.SerializeToString,
            clone__client_dot_proto_dot_data__types__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetValves(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clone.controller.SupervisorGRPC/GetValves',
            clone__client_dot_proto_dot_data__types__pb2.GetNodesRequest.SerializeToString,
            clone__client_dot_controller_dot_proto_dot_supervisor__pb2.ValveListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
