"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetConfigResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIG_FIELD_NUMBER: builtins.int
    config: builtins.str
    def __init__(
        self,
        *,
        config: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["config", b"config"]) -> None: ...

global___GetConfigResponse = GetConfigResponse

@typing.final
class ListStreamsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAMS_FIELD_NUMBER: builtins.int
    @property
    def streams(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        streams: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["streams", b"streams"]) -> None: ...

global___ListStreamsResponse = ListStreamsResponse

@typing.final
class Sink(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    MULTICAST_IFACE_FIELD_NUMBER: builtins.int
    address: builtins.str
    port: builtins.int
    multicast_iface: builtins.str
    def __init__(
        self,
        *,
        address: builtins.str = ...,
        port: builtins.int = ...,
        multicast_iface: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_multicast_iface", b"_multicast_iface", "multicast_iface", b"multicast_iface"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_multicast_iface", b"_multicast_iface", "address", b"address", "multicast_iface", b"multicast_iface", "port", b"port"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_multicast_iface", b"_multicast_iface"]) -> typing.Literal["multicast_iface"] | None: ...

global___Sink = Sink

@typing.final
class ListSinksRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: builtins.int
    stream_id: builtins.str
    def __init__(
        self,
        *,
        stream_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["stream_id", b"stream_id"]) -> None: ...

global___ListSinksRequest = ListSinksRequest

@typing.final
class ListSinksResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SINKS_FIELD_NUMBER: builtins.int
    @property
    def sinks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Sink]: ...
    def __init__(
        self,
        *,
        sinks: collections.abc.Iterable[global___Sink] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["sinks", b"sinks"]) -> None: ...

global___ListSinksResponse = ListSinksResponse

@typing.final
class AddSinkRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: builtins.int
    SINK_FIELD_NUMBER: builtins.int
    stream_id: builtins.str
    @property
    def sink(self) -> global___Sink: ...
    def __init__(
        self,
        *,
        stream_id: builtins.str = ...,
        sink: global___Sink | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["sink", b"sink"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["sink", b"sink", "stream_id", b"stream_id"]) -> None: ...

global___AddSinkRequest = AddSinkRequest

@typing.final
class RemoveSinkRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    stream_id: builtins.str
    address: builtins.str
    port: builtins.int
    def __init__(
        self,
        *,
        stream_id: builtins.str = ...,
        address: builtins.str = ...,
        port: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "port", b"port", "stream_id", b"stream_id"]) -> None: ...

global___RemoveSinkRequest = RemoveSinkRequest

@typing.final
class RemoveAllSinksRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: builtins.int
    stream_id: builtins.str
    def __init__(
        self,
        *,
        stream_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["stream_id", b"stream_id"]) -> None: ...

global___RemoveAllSinksRequest = RemoveAllSinksRequest
