# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clone_client/proto/camera_driver.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'clone_client/proto/camera_driver.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&clone_client/proto/camera_driver.proto\x12\x13\x63lone.camera_driver\x1a\x1bgoogle/protobuf/empty.proto\"#\n\x11GetConfigResponse\x12\x0e\n\x06\x63onfig\x18\x01 \x01(\t\"&\n\x13ListStreamsResponse\x12\x0f\n\x07streams\x18\x01 \x03(\t\"W\n\x04Sink\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\x1c\n\x0fmulticast_iface\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x12\n\x10_multicast_iface\"%\n\x10ListSinksRequest\x12\x11\n\tstream_id\x18\x01 \x01(\t\"=\n\x11ListSinksResponse\x12(\n\x05sinks\x18\x01 \x03(\x0b\x32\x19.clone.camera_driver.Sink\"L\n\x0e\x41\x64\x64SinkRequest\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\'\n\x04sink\x18\x02 \x01(\x0b\x32\x19.clone.camera_driver.Sink\"E\n\x11RemoveSinkRequest\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\"*\n\x15RemoveAllSinksRequest\x12\x11\n\tstream_id\x18\x01 \x01(\t2\xfb\x03\n\x13\x43\x61meraDriverService\x12K\n\tGetConfig\x12\x16.google.protobuf.Empty\x1a&.clone.camera_driver.GetConfigResponse\x12O\n\x0bListStreams\x12\x16.google.protobuf.Empty\x1a(.clone.camera_driver.ListStreamsResponse\x12Z\n\tListSinks\x12%.clone.camera_driver.ListSinksRequest\x1a&.clone.camera_driver.ListSinksResponse\x12\x46\n\x07\x41\x64\x64Sink\x12#.clone.camera_driver.AddSinkRequest\x1a\x16.google.protobuf.Empty\x12L\n\nRemoveSink\x12&.clone.camera_driver.RemoveSinkRequest\x1a\x16.google.protobuf.Empty\x12T\n\x0eRemoveAllSinks\x12*.clone.camera_driver.RemoveAllSinksRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clone_client.proto.camera_driver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCONFIGRESPONSE']._serialized_start=92
  _globals['_GETCONFIGRESPONSE']._serialized_end=127
  _globals['_LISTSTREAMSRESPONSE']._serialized_start=129
  _globals['_LISTSTREAMSRESPONSE']._serialized_end=167
  _globals['_SINK']._serialized_start=169
  _globals['_SINK']._serialized_end=256
  _globals['_LISTSINKSREQUEST']._serialized_start=258
  _globals['_LISTSINKSREQUEST']._serialized_end=295
  _globals['_LISTSINKSRESPONSE']._serialized_start=297
  _globals['_LISTSINKSRESPONSE']._serialized_end=358
  _globals['_ADDSINKREQUEST']._serialized_start=360
  _globals['_ADDSINKREQUEST']._serialized_end=436
  _globals['_REMOVESINKREQUEST']._serialized_start=438
  _globals['_REMOVESINKREQUEST']._serialized_end=507
  _globals['_REMOVEALLSINKSREQUEST']._serialized_start=509
  _globals['_REMOVEALLSINKSREQUEST']._serialized_end=551
  _globals['_CAMERADRIVERSERVICE']._serialized_start=554
  _globals['_CAMERADRIVERSERVICE']._serialized_end=1061
# @@protoc_insertion_point(module_scope)
