"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ErrorType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ErrorTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ErrorType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNSUPPORTED_REQUEST: _ErrorType.ValueType  # 0
    INSTRUCTION: _ErrorType.ValueType  # 1
    INVALID_SERVER_STATE: _ErrorType.ValueType  # 2
    ACQUISITION: _ErrorType.ValueType  # 3
    UNKNOWN: _ErrorType.ValueType  # 4
    RPC_TIMEOUT: _ErrorType.ValueType  # 5
    SERVICE_TIMEOUT: _ErrorType.ValueType  # 6

class ErrorType(_ErrorType, metaclass=_ErrorTypeEnumTypeWrapper): ...

UNSUPPORTED_REQUEST: ErrorType.ValueType  # 0
INSTRUCTION: ErrorType.ValueType  # 1
INVALID_SERVER_STATE: ErrorType.ValueType  # 2
ACQUISITION: ErrorType.ValueType  # 3
UNKNOWN: ErrorType.ValueType  # 4
RPC_TIMEOUT: ErrorType.ValueType  # 5
SERVICE_TIMEOUT: ErrorType.ValueType  # 6
global___ErrorType = ErrorType

class _PulseType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PulseTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PulseType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    IN: _PulseType.ValueType  # 0
    OUT: _PulseType.ValueType  # 1

class PulseType(_PulseType, metaclass=_PulseTypeEnumTypeWrapper): ...

IN: PulseType.ValueType  # 0
OUT: PulseType.ValueType  # 1
global___PulseType = PulseType

@typing_extensions.final
class PulseValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CTRL_TYPE_FIELD_NUMBER: builtins.int
    PULSE_LEN_MS_FIELD_NUMBER: builtins.int
    DELAY_LEN_MS_FIELD_NUMBER: builtins.int
    DURATION_MS_FIELD_NUMBER: builtins.int
    ctrl_type: global___PulseType.ValueType
    pulse_len_ms: builtins.float
    delay_len_ms: builtins.float
    duration_ms: builtins.float
    def __init__(
        self,
        *,
        ctrl_type: global___PulseType.ValueType = ...,
        pulse_len_ms: builtins.float = ...,
        delay_len_ms: builtins.float = ...,
        duration_ms: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ctrl_type", b"ctrl_type", "delay_len_ms", b"delay_len_ms", "duration_ms", b"duration_ms", "pulse_len_ms", b"pulse_len_ms"]) -> None: ...

global___PulseValue = PulseValue

@typing_extensions.final
class Pulse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    IGNORE_FIELD_NUMBER: builtins.int
    @property
    def value(self) -> global___PulseValue: ...
    ignore: builtins.bool
    def __init__(
        self,
        *,
        value: global___PulseValue | None = ...,
        ignore: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["data", b"data", "ignore", b"ignore", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "ignore", b"ignore", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["data", b"data"]) -> typing_extensions.Literal["value", "ignore"] | None: ...

global___Pulse = Pulse

@typing_extensions.final
class MusclePulse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PULSES_FIELD_NUMBER: builtins.int
    @property
    def pulses(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Pulse]: ...
    def __init__(
        self,
        *,
        pulses: collections.abc.Iterable[global___Pulse] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["pulses", b"pulses"]) -> None: ...

global___MusclePulse = MusclePulse

@typing_extensions.final
class Movement(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    IGNORE_FIELD_NUMBER: builtins.int
    value: builtins.float
    ignore: builtins.bool
    def __init__(
        self,
        *,
        value: builtins.float = ...,
        ignore: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["data", b"data", "ignore", b"ignore", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "ignore", b"ignore", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["data", b"data"]) -> typing_extensions.Literal["value", "ignore"] | None: ...

global___Movement = Movement

@typing_extensions.final
class MuscleMovement(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MOVEMENTS_FIELD_NUMBER: builtins.int
    @property
    def movements(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Movement]: ...
    def __init__(
        self,
        *,
        movements: collections.abc.Iterable[global___Movement] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["movements", b"movements"]) -> None: ...

global___MuscleMovement = MuscleMovement

@typing_extensions.final
class MusclePressureSetting(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRESSURES_FIELD_NUMBER: builtins.int
    @property
    def pressures(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        pressures: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["pressures", b"pressures"]) -> None: ...

global___MusclePressureSetting = MusclePressureSetting

@typing_extensions.final
class MusclePressuresState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    PRESSURES_FIELD_NUMBER: builtins.int
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def pressures(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        pressures: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["pressures", b"pressures", "timestamp", b"timestamp"]) -> None: ...

global___MusclePressuresState = MusclePressuresState

@typing_extensions.final
class ErrorInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    error: global___ErrorType.ValueType
    info: builtins.str
    def __init__(
        self,
        *,
        error: global___ErrorType.ValueType = ...,
        info: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["error", b"error", "info", b"info"]) -> None: ...

global___ErrorInfo = ErrorInfo

@typing_extensions.final
class ServerResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    success: builtins.bool
    @property
    def error(self) -> global___ErrorInfo: ...
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        error: global___ErrorInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_error", b"_error", "error", b"error"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_error", b"_error", "error", b"error", "success", b"success"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_error", b"_error"]) -> typing_extensions.Literal["error"] | None: ...

global___ServerResponse = ServerResponse

@typing_extensions.final
class NodeList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___NodeList = NodeList

@typing_extensions.final
class MusclesValveInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class ValuesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.ScalarMap[builtins.int, builtins.str]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Mapping[builtins.int, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___MusclesValveInfo = MusclesValveInfo

@typing_extensions.final
class GetNodesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REDISCOVER_FIELD_NUMBER: builtins.int
    rediscover: builtins.bool
    def __init__(
        self,
        *,
        rediscover: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["rediscover", b"rediscover"]) -> None: ...

global___GetNodesRequest = GetNodesRequest

@typing_extensions.final
class WaterPumpPressure(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRESSURE_FIELD_NUMBER: builtins.int
    pressure: builtins.float
    def __init__(
        self,
        *,
        pressure: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["pressure", b"pressure"]) -> None: ...

global___WaterPumpPressure = WaterPumpPressure
