"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ErrorType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ErrorTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ErrorType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN: _ErrorType.ValueType  # 0
    GOLEM_ERROR: _ErrorType.ValueType  # 1
    WRONG_REQUEST: _ErrorType.ValueType  # 2
    DISABLED_FUNCTIONALITY: _ErrorType.ValueType  # 3

class ErrorType(_ErrorType, metaclass=_ErrorTypeEnumTypeWrapper): ...

UNKNOWN: ErrorType.ValueType  # 0
GOLEM_ERROR: ErrorType.ValueType  # 1
WRONG_REQUEST: ErrorType.ValueType  # 2
DISABLED_FUNCTIONALITY: ErrorType.ValueType  # 3
global___ErrorType = ErrorType

@typing.final
class ErrorInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    SUBTYPE_FIELD_NUMBER: builtins.int
    error: global___ErrorType.ValueType
    info: builtins.str
    subtype: builtins.int
    def __init__(
        self,
        *,
        error: global___ErrorType.ValueType = ...,
        info: builtins.str = ...,
        subtype: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_subtype", b"_subtype", "subtype", b"subtype"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_subtype", b"_subtype", "error", b"error", "info", b"info", "subtype", b"subtype"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_subtype", b"_subtype"]) -> typing.Literal["subtype"] | None: ...

global___ErrorInfo = ErrorInfo

@typing.final
class ServerResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    success: builtins.bool
    @property
    def error(self) -> global___ErrorInfo: ...
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        error: global___ErrorInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_error", b"_error", "error", b"error"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_error", b"_error", "error", b"error", "success", b"success"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_error", b"_error"]) -> typing.Literal["error"] | None: ...

global___ServerResponse = ServerResponse
