# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clone_client/proto/data_types.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'clone_client/proto/data_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#clone_client/proto/data_types.proto\x12\x10\x63lone.data_types\"E\n\tErrorInfo\x12*\n\x05\x65rror\x18\x01 \x01(\x0e\x32\x1b.clone.data_types.ErrorType\x12\x0c\n\x04info\x18\x02 \x01(\t\"\\\n\x0eServerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12/\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1b.clone.data_types.ErrorInfoH\x00\x88\x01\x01\x42\x08\n\x06_error*\xd3\x01\n\tErrorType\x12\x17\n\x13UNSUPPORTED_REQUEST\x10\x00\x12\x0f\n\x0bINSTRUCTION\x10\x01\x12\x18\n\x14INVALID_SERVER_STATE\x10\x02\x12\x0f\n\x0b\x41\x43QUISITION\x10\x03\x12\x0b\n\x07UNKNOWN\x10\x04\x12\x0f\n\x0bRPC_TIMEOUT\x10\x05\x12\x13\n\x0fSERVICE_TIMEOUT\x10\x06\x12\x14\n\x10MISSING_HARDWARE\x10\x07\x12\x1a\n\x16\x44ISABLED_FUNCTIONALITY\x10\x08\x12\x0c\n\x08MISMATCH\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clone_client.proto.data_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERRORTYPE']._serialized_start=223
  _globals['_ERRORTYPE']._serialized_end=434
  _globals['_ERRORINFO']._serialized_start=57
  _globals['_ERRORINFO']._serialized_end=126
  _globals['_SERVERRESPONSE']._serialized_start=128
  _globals['_SERVERRESPONSE']._serialized_end=220
# @@protoc_insertion_point(module_scope)
