"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import clone_client.proto.data_types_pb2
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _PinchValveCommands:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PinchValveCommandsEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PinchValveCommands.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RESERVED: _PinchValveCommands.ValueType  # 0
    ENABLE_STEPPER_DRIVER: _PinchValveCommands.ValueType  # 1
    DISABLE_STEPPER_DRIVER: _PinchValveCommands.ValueType  # 2
    ENABLE_STEPPER_VBOOST: _PinchValveCommands.ValueType  # 3
    DISABLE_STEPPER_VBOOST: _PinchValveCommands.ValueType  # 4

class PinchValveCommands(_PinchValveCommands, metaclass=_PinchValveCommandsEnumTypeWrapper): ...

RESERVED: PinchValveCommands.ValueType  # 0
ENABLE_STEPPER_DRIVER: PinchValveCommands.ValueType  # 1
DISABLE_STEPPER_DRIVER: PinchValveCommands.ValueType  # 2
ENABLE_STEPPER_VBOOST: PinchValveCommands.ValueType  # 3
DISABLE_STEPPER_VBOOST: PinchValveCommands.ValueType  # 4
global___PinchValveCommands = PinchValveCommands

@typing.final
class PauseTelemetryMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAUSE_FIELD_NUMBER: builtins.int
    pause: builtins.bool
    def __init__(
        self,
        *,
        pause: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pause", b"pause"]) -> None: ...

global___PauseTelemetryMessage = PauseTelemetryMessage

@typing.final
class IMUSpecSettingsMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class IMUSpecSettings(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _LearningMode:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _LearningModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[IMUSpecSettingsMessage.IMUSpecSettings._LearningMode.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            Off: IMUSpecSettingsMessage.IMUSpecSettings._LearningMode.ValueType  # 0
            Static: IMUSpecSettingsMessage.IMUSpecSettings._LearningMode.ValueType  # 1
            Dynamic: IMUSpecSettingsMessage.IMUSpecSettings._LearningMode.ValueType  # 2

        class LearningMode(_LearningMode, metaclass=_LearningModeEnumTypeWrapper): ...
        Off: IMUSpecSettingsMessage.IMUSpecSettings.LearningMode.ValueType  # 0
        Static: IMUSpecSettingsMessage.IMUSpecSettings.LearningMode.ValueType  # 1
        Dynamic: IMUSpecSettingsMessage.IMUSpecSettings.LearningMode.ValueType  # 2

        @typing.final
        class TrustFactors(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            ACC_FIELD_NUMBER: builtins.int
            MAG_FIELD_NUMBER: builtins.int
            ACC_EXTERNAL_FIELD_NUMBER: builtins.int
            acc: builtins.float
            mag: builtins.float
            acc_external: builtins.float
            def __init__(
                self,
                *,
                acc: builtins.float = ...,
                mag: builtins.float = ...,
                acc_external: builtins.float = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["acc", b"acc", "acc_external", b"acc_external", "mag", b"mag"]) -> None: ...

        @typing.final
        class GyroBiasThresholds(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            ACC_FIELD_NUMBER: builtins.int
            GYR_FIELD_NUMBER: builtins.int
            MAG_FIELD_NUMBER: builtins.int
            acc: builtins.float
            gyr: builtins.float
            mag: builtins.float
            def __init__(
                self,
                *,
                acc: builtins.float = ...,
                gyr: builtins.float = ...,
                mag: builtins.float = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["acc", b"acc", "gyr", b"gyr", "mag", b"mag"]) -> None: ...

        @typing.final
        class Options(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            USE_GYRO_TEMPERATURE_CALIBRATION_FIELD_NUMBER: builtins.int
            USE_ACC_CALIBRATION_FIELD_NUMBER: builtins.int
            USE_MAG_CALIBRATION_FIELD_NUMBER: builtins.int
            ENABLE_CONTINUOUS_MAG_CALIBRATION_FIELD_NUMBER: builtins.int
            STORE_BIAS_AND_CALIBRATION_PERIODICALLY_FIELD_NUMBER: builtins.int
            ENABLE_MAGNETOMETER_MAGNITUDE_GATING_FIELD_NUMBER: builtins.int
            ENABLE_MAGNETOMETER_ALIGNMENT_GATING_FIELD_NUMBER: builtins.int
            use_gyro_temperature_calibration: builtins.bool
            use_acc_calibration: builtins.bool
            use_mag_calibration: builtins.bool
            enable_continuous_mag_calibration: builtins.bool
            store_bias_and_calibration_periodically: builtins.bool
            enable_magnetometer_magnitude_gating: builtins.bool
            enable_magnetometer_alignment_gating: builtins.bool
            def __init__(
                self,
                *,
                use_gyro_temperature_calibration: builtins.bool = ...,
                use_acc_calibration: builtins.bool = ...,
                use_mag_calibration: builtins.bool = ...,
                enable_continuous_mag_calibration: builtins.bool = ...,
                store_bias_and_calibration_periodically: builtins.bool = ...,
                enable_magnetometer_magnitude_gating: builtins.bool = ...,
                enable_magnetometer_alignment_gating: builtins.bool = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["enable_continuous_mag_calibration", b"enable_continuous_mag_calibration", "enable_magnetometer_alignment_gating", b"enable_magnetometer_alignment_gating", "enable_magnetometer_magnitude_gating", b"enable_magnetometer_magnitude_gating", "store_bias_and_calibration_periodically", b"store_bias_and_calibration_periodically", "use_acc_calibration", b"use_acc_calibration", "use_gyro_temperature_calibration", b"use_gyro_temperature_calibration", "use_mag_calibration", b"use_mag_calibration"]) -> None: ...

        SHOULD_WRITE_FIELD_NUMBER: builtins.int
        TRUST_FACTORS_FIELD_NUMBER: builtins.int
        BIAS_THRESHOLDS_FIELD_NUMBER: builtins.int
        LEARNING_MODE_FIELD_NUMBER: builtins.int
        OPTIONS_FIELD_NUMBER: builtins.int
        should_write: builtins.bool
        learning_mode: global___IMUSpecSettingsMessage.IMUSpecSettings.LearningMode.ValueType
        @property
        def trust_factors(self) -> global___IMUSpecSettingsMessage.IMUSpecSettings.TrustFactors: ...
        @property
        def bias_thresholds(self) -> global___IMUSpecSettingsMessage.IMUSpecSettings.GyroBiasThresholds: ...
        @property
        def options(self) -> global___IMUSpecSettingsMessage.IMUSpecSettings.Options: ...
        def __init__(
            self,
            *,
            should_write: builtins.bool = ...,
            trust_factors: global___IMUSpecSettingsMessage.IMUSpecSettings.TrustFactors | None = ...,
            bias_thresholds: global___IMUSpecSettingsMessage.IMUSpecSettings.GyroBiasThresholds | None = ...,
            learning_mode: global___IMUSpecSettingsMessage.IMUSpecSettings.LearningMode.ValueType = ...,
            options: global___IMUSpecSettingsMessage.IMUSpecSettings.Options | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["bias_thresholds", b"bias_thresholds", "options", b"options", "trust_factors", b"trust_factors"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["bias_thresholds", b"bias_thresholds", "learning_mode", b"learning_mode", "options", b"options", "should_write", b"should_write", "trust_factors", b"trust_factors"]) -> None: ...

    @typing.final
    class SpecSettingsMap(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class SpecSettingsEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.int
            @property
            def value(self) -> global___IMUSpecSettingsMessage.IMUSpecSettings: ...
            def __init__(
                self,
                *,
                key: builtins.int = ...,
                value: global___IMUSpecSettingsMessage.IMUSpecSettings | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

        SPEC_SETTINGS_FIELD_NUMBER: builtins.int
        @property
        def spec_settings(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___IMUSpecSettingsMessage.IMUSpecSettings]: ...
        def __init__(
            self,
            *,
            spec_settings: collections.abc.Mapping[builtins.int, global___IMUSpecSettingsMessage.IMUSpecSettings] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["spec_settings", b"spec_settings"]) -> None: ...

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    @property
    def success(self) -> global___IMUSpecSettingsMessage.SpecSettingsMap: ...
    @property
    def error(self) -> clone_client.proto.data_types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        success: global___IMUSpecSettingsMessage.SpecSettingsMap | None = ...,
        error: clone_client.proto.data_types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["error", b"error", "inner", b"inner", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "inner", b"inner", "success", b"success"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["inner", b"inner"]) -> typing.Literal["success", "error"] | None: ...

global___IMUSpecSettingsMessage = IMUSpecSettingsMessage

@typing.final
class GaussRiderSpecSettingsMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class GaussRiderSpecSettings(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SHOULD_WRITE_FIELD_NUMBER: builtins.int
        REGISTER_ADDRESS_FIELD_NUMBER: builtins.int
        MEASUREMENT_CFG_X_FIELD_NUMBER: builtins.int
        MEASUREMENT_CFG_Y_FIELD_NUMBER: builtins.int
        MEASUREMENT_CFG_Z_FIELD_NUMBER: builtins.int
        MEASUREMENT_CFG_TEMPERATURE_FIELD_NUMBER: builtins.int
        OFFSETS_0_FIELD_NUMBER: builtins.int
        HVAL_P_T0_FIELD_NUMBER: builtins.int
        HVAL_N_T0_FIELD_NUMBER: builtins.int
        TEMPERATURES_FIELD_NUMBER: builtins.int
        HVAL_P_T1_FIELD_NUMBER: builtins.int
        HVAL_N_T1_FIELD_NUMBER: builtins.int
        OFFSETS_1_FIELD_NUMBER: builtins.int
        HVAL_O_P_FIELD_NUMBER: builtins.int
        HVAL_O_N_FIELD_NUMBER: builtins.int
        should_write: builtins.bool
        measurement_cfg_temperature: builtins.int
        @property
        def register_address(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        @property
        def measurement_cfg_x(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        @property
        def measurement_cfg_y(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        @property
        def measurement_cfg_z(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        @property
        def offsets_0(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        @property
        def Hval_P_T0(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        @property
        def Hval_N_T0(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        @property
        def temperatures(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        @property
        def Hval_P_T1(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        @property
        def Hval_N_T1(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        @property
        def offsets_1(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        @property
        def Hval_O_P(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        @property
        def Hval_O_N(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        def __init__(
            self,
            *,
            should_write: builtins.bool = ...,
            register_address: collections.abc.Iterable[builtins.int] | None = ...,
            measurement_cfg_x: collections.abc.Iterable[builtins.int] | None = ...,
            measurement_cfg_y: collections.abc.Iterable[builtins.int] | None = ...,
            measurement_cfg_z: collections.abc.Iterable[builtins.int] | None = ...,
            measurement_cfg_temperature: builtins.int = ...,
            offsets_0: collections.abc.Iterable[builtins.int] | None = ...,
            Hval_P_T0: collections.abc.Iterable[builtins.int] | None = ...,
            Hval_N_T0: collections.abc.Iterable[builtins.int] | None = ...,
            temperatures: collections.abc.Iterable[builtins.int] | None = ...,
            Hval_P_T1: collections.abc.Iterable[builtins.int] | None = ...,
            Hval_N_T1: collections.abc.Iterable[builtins.int] | None = ...,
            offsets_1: collections.abc.Iterable[builtins.int] | None = ...,
            Hval_O_P: collections.abc.Iterable[builtins.int] | None = ...,
            Hval_O_N: collections.abc.Iterable[builtins.int] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["Hval_N_T0", b"Hval_N_T0", "Hval_N_T1", b"Hval_N_T1", "Hval_O_N", b"Hval_O_N", "Hval_O_P", b"Hval_O_P", "Hval_P_T0", b"Hval_P_T0", "Hval_P_T1", b"Hval_P_T1", "measurement_cfg_temperature", b"measurement_cfg_temperature", "measurement_cfg_x", b"measurement_cfg_x", "measurement_cfg_y", b"measurement_cfg_y", "measurement_cfg_z", b"measurement_cfg_z", "offsets_0", b"offsets_0", "offsets_1", b"offsets_1", "register_address", b"register_address", "should_write", b"should_write", "temperatures", b"temperatures"]) -> None: ...

    @typing.final
    class SpecSettingsMap(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class SpecSettingsEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.int
            @property
            def value(self) -> global___GaussRiderSpecSettingsMessage.GaussRiderSpecSettings: ...
            def __init__(
                self,
                *,
                key: builtins.int = ...,
                value: global___GaussRiderSpecSettingsMessage.GaussRiderSpecSettings | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

        SPEC_SETTINGS_FIELD_NUMBER: builtins.int
        @property
        def spec_settings(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___GaussRiderSpecSettingsMessage.GaussRiderSpecSettings]: ...
        def __init__(
            self,
            *,
            spec_settings: collections.abc.Mapping[builtins.int, global___GaussRiderSpecSettingsMessage.GaussRiderSpecSettings] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["spec_settings", b"spec_settings"]) -> None: ...

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    @property
    def success(self) -> global___GaussRiderSpecSettingsMessage.SpecSettingsMap: ...
    @property
    def error(self) -> clone_client.proto.data_types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        success: global___GaussRiderSpecSettingsMessage.SpecSettingsMap | None = ...,
        error: clone_client.proto.data_types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["error", b"error", "inner", b"inner", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "inner", b"inner", "success", b"success"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["inner", b"inner"]) -> typing.Literal["success", "error"] | None: ...

global___GaussRiderSpecSettingsMessage = GaussRiderSpecSettingsMessage

@typing.final
class SendDirectMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: builtins.int
    VALVES_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    valves: builtins.int
    def __init__(
        self,
        *,
        node_id: builtins.int = ...,
        valves: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["node_id", b"node_id", "valves", b"valves"]) -> None: ...

global___SendDirectMessage = SendDirectMessage

@typing.final
class SendManyDirectMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class DataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        value: builtins.int
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    DATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.ScalarMap[builtins.int, builtins.int]: ...
    def __init__(
        self,
        *,
        data: collections.abc.Mapping[builtins.int, builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data"]) -> None: ...

global___SendManyDirectMessage = SendManyDirectMessage

@typing.final
class ImpulseControl(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALVES_FIELD_NUMBER: builtins.int
    DELAY_FIELD_NUMBER: builtins.int
    valves: builtins.int
    delay: builtins.int
    def __init__(
        self,
        *,
        valves: builtins.int = ...,
        delay: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["delay", b"delay", "valves", b"valves"]) -> None: ...

global___ImpulseControl = ImpulseControl

@typing.final
class SendImpulseMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: builtins.int
    CONTROL_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    @property
    def control(self) -> global___ImpulseControl: ...
    def __init__(
        self,
        *,
        node_id: builtins.int = ...,
        control: global___ImpulseControl | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["control", b"control"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["control", b"control", "node_id", b"node_id"]) -> None: ...

global___SendImpulseMessage = SendImpulseMessage

@typing.final
class SendManyImpulseMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class DataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> global___ImpulseControl: ...
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: global___ImpulseControl | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    DATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___ImpulseControl]: ...
    def __init__(
        self,
        *,
        data: collections.abc.Mapping[builtins.int, global___ImpulseControl] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data"]) -> None: ...

global___SendManyImpulseMessage = SendManyImpulseMessage

@typing.final
class SendPulseMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: builtins.int
    VALVE_ID_FIELD_NUMBER: builtins.int
    PULSE_LEN_MS_FIELD_NUMBER: builtins.int
    DELAY_LEN_MS_FIELD_NUMBER: builtins.int
    DURATION_MS_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    valve_id: builtins.int
    pulse_len_ms: builtins.int
    delay_len_ms: builtins.int
    duration_ms: builtins.int
    def __init__(
        self,
        *,
        node_id: builtins.int = ...,
        valve_id: builtins.int = ...,
        pulse_len_ms: builtins.int = ...,
        delay_len_ms: builtins.int = ...,
        duration_ms: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["delay_len_ms", b"delay_len_ms", "duration_ms", b"duration_ms", "node_id", b"node_id", "pulse_len_ms", b"pulse_len_ms", "valve_id", b"valve_id"]) -> None: ...

global___SendPulseMessage = SendPulseMessage

@typing.final
class PressureControl(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRESSURES_FIELD_NUMBER: builtins.int
    @property
    def pressures(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        pressures: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pressures", b"pressures"]) -> None: ...

global___PressureControl = PressureControl

@typing.final
class SendManyPressureMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class DataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> global___PressureControl: ...
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: global___PressureControl | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    DATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___PressureControl]: ...
    def __init__(
        self,
        *,
        data: collections.abc.Mapping[builtins.int, global___PressureControl] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data"]) -> None: ...

global___SendManyPressureMessage = SendManyPressureMessage

@typing.final
class PinchValveControl(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _PositionsType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _PositionsTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[PinchValveControl._PositionsType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        POSITION_UNKNOWN: PinchValveControl._PositionsType.ValueType  # 0
        """Cam position unknown"""
        BOTH_CLOSED: PinchValveControl._PositionsType.ValueType  # 1
        """Both inlet and outlet are closed"""
        BOTH_OPENED: PinchValveControl._PositionsType.ValueType  # 2
        """Both inlet and outlet are opened, AKA flush"""
        INLET_FULLY_OPENED: PinchValveControl._PositionsType.ValueType  # 3
        """Inlet valve fully opened"""
        INLET_PARTIALLY_OPENED: PinchValveControl._PositionsType.ValueType  # 4
        """Inlet valve opened, but only partially"""
        OUTLET_FULLY_OPENED: PinchValveControl._PositionsType.ValueType  # 5
        """Outlet valve fully opened"""
        OUTLET_PARTIALLY_OPENED: PinchValveControl._PositionsType.ValueType  # 6
        """Outlet valve opened, but only partially"""

    class PositionsType(_PositionsType, metaclass=_PositionsTypeEnumTypeWrapper): ...
    POSITION_UNKNOWN: PinchValveControl.PositionsType.ValueType  # 0
    """Cam position unknown"""
    BOTH_CLOSED: PinchValveControl.PositionsType.ValueType  # 1
    """Both inlet and outlet are closed"""
    BOTH_OPENED: PinchValveControl.PositionsType.ValueType  # 2
    """Both inlet and outlet are opened, AKA flush"""
    INLET_FULLY_OPENED: PinchValveControl.PositionsType.ValueType  # 3
    """Inlet valve fully opened"""
    INLET_PARTIALLY_OPENED: PinchValveControl.PositionsType.ValueType  # 4
    """Inlet valve opened, but only partially"""
    OUTLET_FULLY_OPENED: PinchValveControl.PositionsType.ValueType  # 5
    """Outlet valve fully opened"""
    OUTLET_PARTIALLY_OPENED: PinchValveControl.PositionsType.ValueType  # 6
    """Outlet valve opened, but only partially"""

    class _ControlMode:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ControlModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[PinchValveControl._ControlMode.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        RESERVED: PinchValveControl._ControlMode.ValueType  # 0
        ANGLE: PinchValveControl._ControlMode.ValueType  # 1
        PRESSURE: PinchValveControl._ControlMode.ValueType  # 2
        POSITIONS: PinchValveControl._ControlMode.ValueType  # 3

    class ControlMode(_ControlMode, metaclass=_ControlModeEnumTypeWrapper): ...
    RESERVED: PinchValveControl.ControlMode.ValueType  # 0
    ANGLE: PinchValveControl.ControlMode.ValueType  # 1
    PRESSURE: PinchValveControl.ControlMode.ValueType  # 2
    POSITIONS: PinchValveControl.ControlMode.ValueType  # 3

    MODE_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    mode: global___PinchValveControl.ControlMode.ValueType
    value: builtins.int
    def __init__(
        self,
        *,
        mode: global___PinchValveControl.ControlMode.ValueType = ...,
        value: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["mode", b"mode", "value", b"value"]) -> None: ...

global___PinchValveControl = PinchValveControl

@typing.final
class SendPinchValveControlMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: builtins.int
    CONTROL_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    @property
    def control(self) -> global___PinchValveControl: ...
    def __init__(
        self,
        *,
        node_id: builtins.int = ...,
        control: global___PinchValveControl | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["control", b"control"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["control", b"control", "node_id", b"node_id"]) -> None: ...

global___SendPinchValveControlMessage = SendPinchValveControlMessage

@typing.final
class SendManyPinchValveControlMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class DataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> global___PinchValveControl: ...
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: global___PinchValveControl | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    DATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___PinchValveControl]: ...
    def __init__(
        self,
        *,
        data: collections.abc.Mapping[builtins.int, global___PinchValveControl] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data"]) -> None: ...

global___SendManyPinchValveControlMessage = SendManyPinchValveControlMessage

@typing.final
class HydraControlMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _PositionsType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _PositionsTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[HydraControlMessage._PositionsType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        POSITION_UNKNOWN: HydraControlMessage._PositionsType.ValueType  # 0
        """Cam position unknown"""
        BOTH_CLOSED: HydraControlMessage._PositionsType.ValueType  # 1
        """Both inlet and outlet are closed"""
        BOTH_OPENED: HydraControlMessage._PositionsType.ValueType  # 2
        """Both inlet and outlet are opened, AKA flush"""
        INLET_FULLY_OPENED: HydraControlMessage._PositionsType.ValueType  # 3
        """Inlet valve fully opened"""
        INLET_PARTIALLY_OPENED: HydraControlMessage._PositionsType.ValueType  # 4
        """Inlet valve opened, but only partially"""
        OUTLET_FULLY_OPENED: HydraControlMessage._PositionsType.ValueType  # 5
        """Outlet valve fully opened"""
        OUTLET_PARTIALLY_OPENED: HydraControlMessage._PositionsType.ValueType  # 6
        """Outlet valve opened, but only partially"""

    class PositionsType(_PositionsType, metaclass=_PositionsTypeEnumTypeWrapper): ...
    POSITION_UNKNOWN: HydraControlMessage.PositionsType.ValueType  # 0
    """Cam position unknown"""
    BOTH_CLOSED: HydraControlMessage.PositionsType.ValueType  # 1
    """Both inlet and outlet are closed"""
    BOTH_OPENED: HydraControlMessage.PositionsType.ValueType  # 2
    """Both inlet and outlet are opened, AKA flush"""
    INLET_FULLY_OPENED: HydraControlMessage.PositionsType.ValueType  # 3
    """Inlet valve fully opened"""
    INLET_PARTIALLY_OPENED: HydraControlMessage.PositionsType.ValueType  # 4
    """Inlet valve opened, but only partially"""
    OUTLET_FULLY_OPENED: HydraControlMessage.PositionsType.ValueType  # 5
    """Outlet valve fully opened"""
    OUTLET_PARTIALLY_OPENED: HydraControlMessage.PositionsType.ValueType  # 6
    """Outlet valve opened, but only partially"""

    @typing.final
    class Angles(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ANGLES_FIELD_NUMBER: builtins.int
        @property
        def angles(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
        def __init__(
            self,
            *,
            angles: collections.abc.Iterable[builtins.float] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["angles", b"angles"]) -> None: ...

    @typing.final
    class Pressures(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        PRESSURES_FIELD_NUMBER: builtins.int
        @property
        def pressures(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        def __init__(
            self,
            *,
            pressures: collections.abc.Iterable[builtins.int] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["pressures", b"pressures"]) -> None: ...

    @typing.final
    class Positions(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        POSITIONS_FIELD_NUMBER: builtins.int
        @property
        def positions(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___HydraControlMessage.PositionsType.ValueType]: ...
        def __init__(
            self,
            *,
            positions: collections.abc.Iterable[global___HydraControlMessage.PositionsType.ValueType] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["positions", b"positions"]) -> None: ...

    @typing.final
    class Speeds(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SPEEDS_FIELD_NUMBER: builtins.int
        @property
        def speeds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        def __init__(
            self,
            *,
            speeds: collections.abc.Iterable[builtins.int] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["speeds", b"speeds"]) -> None: ...

    ANGLES_FIELD_NUMBER: builtins.int
    PRESSURES_FIELD_NUMBER: builtins.int
    POSITIONS_FIELD_NUMBER: builtins.int
    SPEEDS_FIELD_NUMBER: builtins.int
    @property
    def angles(self) -> global___HydraControlMessage.Angles: ...
    @property
    def pressures(self) -> global___HydraControlMessage.Pressures: ...
    @property
    def positions(self) -> global___HydraControlMessage.Positions: ...
    @property
    def speeds(self) -> global___HydraControlMessage.Speeds: ...
    def __init__(
        self,
        *,
        angles: global___HydraControlMessage.Angles | None = ...,
        pressures: global___HydraControlMessage.Pressures | None = ...,
        positions: global___HydraControlMessage.Positions | None = ...,
        speeds: global___HydraControlMessage.Speeds | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["angles", b"angles", "positions", b"positions", "pressures", b"pressures", "speeds", b"speeds", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["angles", b"angles", "positions", b"positions", "pressures", b"pressures", "speeds", b"speeds", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["value", b"value"]) -> typing.Literal["angles", "pressures", "positions", "speeds"] | None: ...

global___HydraControlMessage = HydraControlMessage

@typing.final
class SendHydraControlMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: builtins.int
    CONTROL_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    @property
    def control(self) -> global___HydraControlMessage: ...
    def __init__(
        self,
        *,
        node_id: builtins.int = ...,
        control: global___HydraControlMessage | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["control", b"control"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["control", b"control", "node_id", b"node_id"]) -> None: ...

global___SendHydraControlMessage = SendHydraControlMessage

@typing.final
class SendManyHydraControlMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class DataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> global___HydraControlMessage: ...
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: global___HydraControlMessage | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    DATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___HydraControlMessage]: ...
    def __init__(
        self,
        *,
        data: collections.abc.Mapping[builtins.int, global___HydraControlMessage] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data"]) -> None: ...

global___SendManyHydraControlMessage = SendManyHydraControlMessage

@typing.final
class GetNodesMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRODUCT_ID_FIELD_NUMBER: builtins.int
    product_id: builtins.int
    """bool rediscover = 1;"""
    def __init__(
        self,
        *,
        product_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_product_id", b"_product_id", "product_id", b"product_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_product_id", b"_product_id", "product_id", b"product_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_product_id", b"_product_id"]) -> typing.Literal["product_id"] | None: ...

global___GetNodesMessage = GetNodesMessage

@typing.final
class BusDevice(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: builtins.int
    PRODUCT_ID_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    product_id: builtins.int
    def __init__(
        self,
        *,
        node_id: builtins.int = ...,
        product_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["node_id", b"node_id", "product_id", b"product_id"]) -> None: ...

global___BusDevice = BusDevice

@typing.final
class NodeList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODES_FIELD_NUMBER: builtins.int
    @property
    def nodes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BusDevice]: ...
    def __init__(
        self,
        *,
        nodes: collections.abc.Iterable[global___BusDevice] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["nodes", b"nodes"]) -> None: ...

global___NodeList = NodeList

@typing.final
class NodeMap(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class NodesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___NodeList: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___NodeList | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    NODES_FIELD_NUMBER: builtins.int
    @property
    def nodes(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___NodeList]: ...
    def __init__(
        self,
        *,
        nodes: collections.abc.Mapping[builtins.str, global___NodeList] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["nodes", b"nodes"]) -> None: ...

global___NodeMap = NodeMap

@typing.final
class SendPinchValveCommandMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    command: global___PinchValveCommands.ValueType
    def __init__(
        self,
        *,
        node_id: builtins.int = ...,
        command: global___PinchValveCommands.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["command", b"command", "node_id", b"node_id"]) -> None: ...

global___SendPinchValveCommandMessage = SendPinchValveCommandMessage

@typing.final
class SendManyPinchValveCommandMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class CommandsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        value: global___PinchValveCommands.ValueType
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: global___PinchValveCommands.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    COMMANDS_FIELD_NUMBER: builtins.int
    @property
    def commands(self) -> google.protobuf.internal.containers.ScalarMap[builtins.int, global___PinchValveCommands.ValueType]: ...
    def __init__(
        self,
        *,
        commands: collections.abc.Mapping[builtins.int, global___PinchValveCommands.ValueType] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["commands", b"commands"]) -> None: ...

global___SendManyPinchValveCommandMessage = SendManyPinchValveCommandMessage

@typing.final
class PingNodeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: builtins.int
    BUS_NAME_FIELD_NUMBER: builtins.int
    TIMEOUT_US_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    bus_name: builtins.str
    timeout_us: builtins.int
    def __init__(
        self,
        *,
        node_id: builtins.int = ...,
        bus_name: builtins.str = ...,
        timeout_us: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bus_name", b"bus_name", "node_id", b"node_id", "timeout_us", b"timeout_us"]) -> None: ...

global___PingNodeMessage = PingNodeMessage

@typing.final
class DiscoveryMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class DiscoveryRange(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        START_NODE_FIELD_NUMBER: builtins.int
        END_NODE_FIELD_NUMBER: builtins.int
        start_node: builtins.int
        end_node: builtins.int
        def __init__(
            self,
            *,
            start_node: builtins.int = ...,
            end_node: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["end_node", b"end_node", "start_node", b"start_node"]) -> None: ...

    BUS_NAME_FIELD_NUMBER: builtins.int
    TIMEOUT_US_FIELD_NUMBER: builtins.int
    DISCOVERY_RANGES_FIELD_NUMBER: builtins.int
    DISCOVERY_BLACKLIST_FIELD_NUMBER: builtins.int
    bus_name: builtins.str
    timeout_us: builtins.int
    @property
    def discovery_ranges(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DiscoveryMessage.DiscoveryRange]:
        """for mass discovery enter 0 - 254 range, optionally
        eliminating some nodes with a blacklist
        """

    @property
    def discovery_blacklist(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        bus_name: builtins.str = ...,
        timeout_us: builtins.int = ...,
        discovery_ranges: collections.abc.Iterable[global___DiscoveryMessage.DiscoveryRange] | None = ...,
        discovery_blacklist: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bus_name", b"bus_name", "discovery_blacklist", b"discovery_blacklist", "discovery_ranges", b"discovery_ranges", "timeout_us", b"timeout_us"]) -> None: ...

global___DiscoveryMessage = DiscoveryMessage

@typing.final
class DiscoveryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVER_RESPONSE_FIELD_NUMBER: builtins.int
    NODE_IDS_FIELD_NUMBER: builtins.int
    @property
    def server_response(self) -> clone_client.proto.data_types_pb2.ServerResponse: ...
    @property
    def node_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        server_response: clone_client.proto.data_types_pb2.ServerResponse | None = ...,
        node_ids: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["server_response", b"server_response"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["node_ids", b"node_ids", "server_response", b"server_response"]) -> None: ...

global___DiscoveryResponse = DiscoveryResponse

@typing.final
class GetNodesSettingsMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUS_NAME_FIELD_NUMBER: builtins.int
    NODE_IDS_FIELD_NUMBER: builtins.int
    TIMEOUT_US_FIELD_NUMBER: builtins.int
    bus_name: builtins.str
    timeout_us: builtins.int
    @property
    def node_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        bus_name: builtins.str = ...,
        node_ids: collections.abc.Iterable[builtins.int] | None = ...,
        timeout_us: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bus_name", b"bus_name", "node_ids", b"node_ids", "timeout_us", b"timeout_us"]) -> None: ...

global___GetNodesSettingsMessage = GetNodesSettingsMessage

@typing.final
class NodeGenericSettings(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: builtins.int
    PRODUCT_ID_FIELD_NUMBER: builtins.int
    PCB_ID_FIELD_NUMBER: builtins.int
    _VALVE_HOLD_DUTY_FIELD_NUMBER: builtins.int
    _PAD3_FIELD_NUMBER: builtins.int
    DEVICE_RANDOM_ID_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    product_id: builtins.int
    pcb_id: builtins.int
    _valve_hold_duty: builtins.int
    """legacy"""
    _pad3: builtins.int
    device_random_id: builtins.int
    def __init__(
        self,
        *,
        node_id: builtins.int = ...,
        product_id: builtins.int = ...,
        pcb_id: builtins.int = ...,
        _valve_hold_duty: builtins.int = ...,
        _pad3: builtins.int = ...,
        device_random_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["_pad3", b"_pad3", "_valve_hold_duty", b"_valve_hold_duty", "device_random_id", b"device_random_id", "node_id", b"node_id", "pcb_id", b"pcb_id", "product_id", b"product_id"]) -> None: ...

global___NodeGenericSettings = NodeGenericSettings

@typing.final
class GetNodesSettingsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class NodeSettingsWrapper(google.protobuf.message.Message):
        """if None then no response was received"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SETTINGS_FIELD_NUMBER: builtins.int
        @property
        def settings(self) -> global___NodeGenericSettings: ...
        def __init__(
            self,
            *,
            settings: global___NodeGenericSettings | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_settings", b"_settings", "settings", b"settings"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_settings", b"_settings", "settings", b"settings"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["_settings", b"_settings"]) -> typing.Literal["settings"] | None: ...

    @typing.final
    class SettingsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> global___GetNodesSettingsResponse.NodeSettingsWrapper: ...
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: global___GetNodesSettingsResponse.NodeSettingsWrapper | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    SETTINGS_FIELD_NUMBER: builtins.int
    @property
    def settings(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___GetNodesSettingsResponse.NodeSettingsWrapper]:
        """if whole map is empty than no such a bus exists"""

    def __init__(
        self,
        *,
        settings: collections.abc.Mapping[builtins.int, global___GetNodesSettingsResponse.NodeSettingsWrapper] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["settings", b"settings"]) -> None: ...

global___GetNodesSettingsResponse = GetNodesSettingsResponse

@typing.final
class HwDriverErrors(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class BusesErrorsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> clone_client.proto.data_types_pb2.ErrorList: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: clone_client.proto.data_types_pb2.ErrorList | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    HW_DRIVER_ERRORS_FIELD_NUMBER: builtins.int
    BUSES_ERRORS_FIELD_NUMBER: builtins.int
    @property
    def hw_driver_errors(self) -> clone_client.proto.data_types_pb2.ErrorList.ErrorList:
        """inner error list, cause this field is implicitly optional"""

    @property
    def buses_errors(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, clone_client.proto.data_types_pb2.ErrorList]: ...
    def __init__(
        self,
        *,
        hw_driver_errors: clone_client.proto.data_types_pb2.ErrorList.ErrorList | None = ...,
        buses_errors: collections.abc.Mapping[builtins.str, clone_client.proto.data_types_pb2.ErrorList] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["hw_driver_errors", b"hw_driver_errors"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["buses_errors", b"buses_errors", "hw_driver_errors", b"hw_driver_errors"]) -> None: ...

global___HwDriverErrors = HwDriverErrors
