"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import clone_client.proto.data_types_pb2
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _TelemetryConfig:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TelemetryConfigEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TelemetryConfig.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PRESSURE: _TelemetryConfig.ValueType  # 0
    IMU: _TelemetryConfig.ValueType  # 1
    ALL: _TelemetryConfig.ValueType  # 2

class TelemetryConfig(_TelemetryConfig, metaclass=_TelemetryConfigEnumTypeWrapper): ...

PRESSURE: TelemetryConfig.ValueType  # 0
IMU: TelemetryConfig.ValueType  # 1
ALL: TelemetryConfig.ValueType  # 2
global___TelemetryConfig = TelemetryConfig

@typing.final
class IMUData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _SignalState:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _SignalStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[IMUData._SignalState.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: IMUData._SignalState.ValueType  # 0
        """*< Unknown / uninitialized"""
        VALID: IMUData._SignalState.ValueType  # 1
        """*< Healthy and trusted"""
        SUSPECT: IMUData._SignalState.ValueType  # 2
        """*< Usable but near limits"""
        RECONFIG_FAILED: IMUData._SignalState.ValueType  # 3
        """*< Last re-config attempt failed; using previous settings"""
        INVALID: IMUData._SignalState.ValueType  # 4
        """*< Fails gating or plausibility checks"""
        NOT_AVAILABLE: IMUData._SignalState.ValueType  # 5
        """*< No fresh data or sensor inactive"""
        UNDER_CALIBRATION: IMUData._SignalState.ValueType  # 6
        """*< Under user calibration"""
        INIT: IMUData._SignalState.ValueType  # 7
        """*< Initialization value / default"""

    class SignalState(_SignalState, metaclass=_SignalStateEnumTypeWrapper): ...
    UNKNOWN: IMUData.SignalState.ValueType  # 0
    """*< Unknown / uninitialized"""
    VALID: IMUData.SignalState.ValueType  # 1
    """*< Healthy and trusted"""
    SUSPECT: IMUData.SignalState.ValueType  # 2
    """*< Usable but near limits"""
    RECONFIG_FAILED: IMUData.SignalState.ValueType  # 3
    """*< Last re-config attempt failed; using previous settings"""
    INVALID: IMUData.SignalState.ValueType  # 4
    """*< Fails gating or plausibility checks"""
    NOT_AVAILABLE: IMUData.SignalState.ValueType  # 5
    """*< No fresh data or sensor inactive"""
    UNDER_CALIBRATION: IMUData.SignalState.ValueType  # 6
    """*< Under user calibration"""
    INIT: IMUData.SignalState.ValueType  # 7
    """*< Initialization value / default"""

    class _CalibrationStatusValue:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _CalibrationStatusValueEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[IMUData._CalibrationStatusValue.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN_OR_NOT_CALIBRATED: IMUData._CalibrationStatusValue.ValueType  # 0
        POOR: IMUData._CalibrationStatusValue.ValueType  # 1
        OK: IMUData._CalibrationStatusValue.ValueType  # 2
        GOOD: IMUData._CalibrationStatusValue.ValueType  # 3
        ONGOING: IMUData._CalibrationStatusValue.ValueType  # 4

    class CalibrationStatusValue(_CalibrationStatusValue, metaclass=_CalibrationStatusValueEnumTypeWrapper): ...
    UNKNOWN_OR_NOT_CALIBRATED: IMUData.CalibrationStatusValue.ValueType  # 0
    POOR: IMUData.CalibrationStatusValue.ValueType  # 1
    OK: IMUData.CalibrationStatusValue.ValueType  # 2
    GOOD: IMUData.CalibrationStatusValue.ValueType  # 3
    ONGOING: IMUData.CalibrationStatusValue.ValueType  # 4

    @typing.final
    class CalibrationStatusPacked(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        MAG_CALIB_STATUS_FIELD_NUMBER: builtins.int
        ACC_CALIB_STATUS_FIELD_NUMBER: builtins.int
        GYR_CALIB_STATUS_FIELD_NUMBER: builtins.int
        GYR_TIME_SINCE_LAST_BIAS_CALIB_MS_FIELD_NUMBER: builtins.int
        mag_calib_status: global___IMUData.CalibrationStatusValue.ValueType
        acc_calib_status: global___IMUData.CalibrationStatusValue.ValueType
        gyr_calib_status: global___IMUData.CalibrationStatusValue.ValueType
        gyr_time_since_last_bias_calib_ms: builtins.int
        def __init__(
            self,
            *,
            mag_calib_status: global___IMUData.CalibrationStatusValue.ValueType = ...,
            acc_calib_status: global___IMUData.CalibrationStatusValue.ValueType = ...,
            gyr_calib_status: global___IMUData.CalibrationStatusValue.ValueType = ...,
            gyr_time_since_last_bias_calib_ms: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["acc_calib_status", b"acc_calib_status", "gyr_calib_status", b"gyr_calib_status", "gyr_time_since_last_bias_calib_ms", b"gyr_time_since_last_bias_calib_ms", "mag_calib_status", b"mag_calib_status"]) -> None: ...

    NODE_ID_FIELD_NUMBER: builtins.int
    W_FIELD_NUMBER: builtins.int
    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    SIGNAL_STATE_FIELD_NUMBER: builtins.int
    CALIBRATION_STATUS_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    w: builtins.float
    x: builtins.float
    y: builtins.float
    z: builtins.float
    signal_state: global___IMUData.SignalState.ValueType
    """6, 7, 8"""
    @property
    def calibration_status(self) -> global___IMUData.CalibrationStatusPacked: ...
    def __init__(
        self,
        *,
        node_id: builtins.int = ...,
        w: builtins.float = ...,
        x: builtins.float = ...,
        y: builtins.float = ...,
        z: builtins.float = ...,
        signal_state: global___IMUData.SignalState.ValueType = ...,
        calibration_status: global___IMUData.CalibrationStatusPacked | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["calibration_status", b"calibration_status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["calibration_status", b"calibration_status", "node_id", b"node_id", "signal_state", b"signal_state", "w", b"w", "x", b"x", "y", b"y", "z", b"z"]) -> None: ...

global___IMUData = IMUData

@typing.final
class MagneticSensor(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MagneticPixel(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        X_FIELD_NUMBER: builtins.int
        Y_FIELD_NUMBER: builtins.int
        Z_FIELD_NUMBER: builtins.int
        x: builtins.int
        y: builtins.int
        z: builtins.int
        def __init__(
            self,
            *,
            x: builtins.int = ...,
            y: builtins.int = ...,
            z: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["x", b"x", "y", b"y", "z", b"z"]) -> None: ...

    PIXELS_FIELD_NUMBER: builtins.int
    TEMPERATURE_FIELD_NUMBER: builtins.int
    temperature: builtins.int
    @property
    def pixels(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MagneticSensor.MagneticPixel]: ...
    def __init__(
        self,
        *,
        pixels: collections.abc.Iterable[global___MagneticSensor.MagneticPixel] | None = ...,
        temperature: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pixels", b"pixels", "temperature", b"temperature"]) -> None: ...

global___MagneticSensor = MagneticSensor

@typing.final
class GaussRiderRaw(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: builtins.int
    SENSOR_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    @property
    def sensor(self) -> global___MagneticSensor: ...
    def __init__(
        self,
        *,
        node_id: builtins.int = ...,
        sensor: global___MagneticSensor | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["sensor", b"sensor"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["node_id", b"node_id", "sensor", b"sensor"]) -> None: ...

global___GaussRiderRaw = GaussRiderRaw

@typing.final
class SensorData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class BfieldsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> global___Bfield: ...
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: global___Bfield | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    PRESSURES_FIELD_NUMBER: builtins.int
    IMU_FIELD_NUMBER: builtins.int
    GAUSS_RIDER_DATA_FIELD_NUMBER: builtins.int
    BFIELDS_FIELD_NUMBER: builtins.int
    @property
    def pressures(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def imu(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IMUData]: ...
    @property
    def gauss_rider_data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GaussRiderRaw]:
        """repeated MagneticHubRaw magnetic_data=3; // Unprocessed magnetic hub's data - currently also here
        Unprocessed gauss rider's data
        """

    @property
    def bfields(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___Bfield]: ...
    def __init__(
        self,
        *,
        pressures: collections.abc.Iterable[builtins.float] | None = ...,
        imu: collections.abc.Iterable[global___IMUData] | None = ...,
        gauss_rider_data: collections.abc.Iterable[global___GaussRiderRaw] | None = ...,
        bfields: collections.abc.Mapping[builtins.int, global___Bfield] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bfields", b"bfields", "gauss_rider_data", b"gauss_rider_data", "imu", b"imu", "pressures", b"pressures"]) -> None: ...

global___SensorData = SensorData

@typing.final
class Quaternion(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    W_FIELD_NUMBER: builtins.int
    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    w: builtins.float
    x: builtins.float
    y: builtins.float
    z: builtins.float
    def __init__(
        self,
        *,
        w: builtins.float = ...,
        x: builtins.float = ...,
        y: builtins.float = ...,
        z: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["w", b"w", "x", b"x", "y", b"y", "z", b"z"]) -> None: ...

global___Quaternion = Quaternion

@typing.final
class PoseEstimationData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class PoseEstimationEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___Quaternion: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___Quaternion | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    POSE_ESTIMATION_FIELD_NUMBER: builtins.int
    @property
    def pose_estimation(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Quaternion]: ...
    def __init__(
        self,
        *,
        pose_estimation: collections.abc.Mapping[builtins.str, global___Quaternion] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pose_estimation", b"pose_estimation"]) -> None: ...

global___PoseEstimationData = PoseEstimationData

@typing.final
class Mat3(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COL0_FIELD_NUMBER: builtins.int
    COL1_FIELD_NUMBER: builtins.int
    COL2_FIELD_NUMBER: builtins.int
    @property
    def col0(self) -> global___Vec3: ...
    @property
    def col1(self) -> global___Vec3: ...
    @property
    def col2(self) -> global___Vec3: ...
    def __init__(
        self,
        *,
        col0: global___Vec3 | None = ...,
        col1: global___Vec3 | None = ...,
        col2: global___Vec3 | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["col0", b"col0", "col1", b"col1", "col2", b"col2"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["col0", b"col0", "col1", b"col1", "col2", b"col2"]) -> None: ...

global___Mat3 = Mat3

@typing.final
class AxisToHingeBindings(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class AxisToHingeBindingsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    AXIS_TO_HINGE_BINDINGS_FIELD_NUMBER: builtins.int
    @property
    def axis_to_hinge_bindings(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        axis_to_hinge_bindings: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["axis_to_hinge_bindings", b"axis_to_hinge_bindings"]) -> None: ...

global___AxisToHingeBindings = AxisToHingeBindings

@typing.final
class JointFrames(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Frame(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        R_WJ_FIELD_NUMBER: builtins.int
        ORIGIN_W_FIELD_NUMBER: builtins.int
        @property
        def r_wj(self) -> global___Mat3: ...
        @property
        def origin_w(self) -> global___Vec3: ...
        def __init__(
            self,
            *,
            r_wj: global___Mat3 | None = ...,
            origin_w: global___Vec3 | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["origin_w", b"origin_w", "r_wj", b"r_wj"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["origin_w", b"origin_w", "r_wj", b"r_wj"]) -> None: ...

    @typing.final
    class FramesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___JointFrames.Frame: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___JointFrames.Frame | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    FRAMES_FIELD_NUMBER: builtins.int
    @property
    def frames(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___JointFrames.Frame]: ...
    def __init__(
        self,
        *,
        frames: collections.abc.Mapping[builtins.str, global___JointFrames.Frame] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["frames", b"frames"]) -> None: ...

global___JointFrames = JointFrames

@typing.final
class SensorGeometry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRAME_WS_FIELD_NUMBER: builtins.int
    ORIGIN_W_FIELD_NUMBER: builtins.int
    @property
    def frame_wS(self) -> global___Mat3: ...
    @property
    def origin_w(self) -> global___Vec3: ...
    def __init__(
        self,
        *,
        frame_wS: global___Mat3 | None = ...,
        origin_w: global___Vec3 | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["frame_wS", b"frame_wS", "origin_w", b"origin_w"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["frame_wS", b"frame_wS", "origin_w", b"origin_w"]) -> None: ...

global___SensorGeometry = SensorGeometry

@typing.final
class MagnetGeometry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORIGIN_W_FIELD_NUMBER: builtins.int
    BASE_Z_IN_SENSOR_FIELD_NUMBER: builtins.int
    @property
    def origin_w(self) -> global___Vec3: ...
    @property
    def base_z_in_sensor(self) -> global___Vec3: ...
    def __init__(
        self,
        *,
        origin_w: global___Vec3 | None = ...,
        base_z_in_sensor: global___Vec3 | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["base_z_in_sensor", b"base_z_in_sensor", "origin_w", b"origin_w"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["base_z_in_sensor", b"base_z_in_sensor", "origin_w", b"origin_w"]) -> None: ...

global___MagnetGeometry = MagnetGeometry

@typing.final
class DipoleSeed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POSITION_FIELD_NUMBER: builtins.int
    DIRECTION_FIELD_NUMBER: builtins.int
    @property
    def position(self) -> global___Vec3: ...
    @property
    def direction(self) -> global___Vec3: ...
    def __init__(
        self,
        *,
        position: global___Vec3 | None = ...,
        direction: global___Vec3 | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["direction", b"direction", "position", b"position"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["direction", b"direction", "position", b"position"]) -> None: ...

global___DipoleSeed = DipoleSeed

@typing.final
class SensorMapping(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLONE_SENSOR_ID_FIELD_NUMBER: builtins.int
    MAGNET_LOCAL_AXIS_FIELD_NUMBER: builtins.int
    SENSOR_MAGNET_INVERSION_FIELD_NUMBER: builtins.int
    R_CORR_FIELD_NUMBER: builtins.int
    clone_sensor_id: builtins.str
    sensor_magnet_inversion: builtins.bool
    @property
    def magnet_local_axis(self) -> global___Vec3: ...
    @property
    def R_corr(self) -> global___Mat3: ...
    def __init__(
        self,
        *,
        clone_sensor_id: builtins.str = ...,
        magnet_local_axis: global___Vec3 | None = ...,
        sensor_magnet_inversion: builtins.bool = ...,
        R_corr: global___Mat3 | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["R_corr", b"R_corr", "magnet_local_axis", b"magnet_local_axis"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["R_corr", b"R_corr", "clone_sensor_id", b"clone_sensor_id", "magnet_local_axis", b"magnet_local_axis", "sensor_magnet_inversion", b"sensor_magnet_inversion"]) -> None: ...

global___SensorMapping = SensorMapping

@typing.final
class JointModelInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class JointModel(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        JOINT_FRAMES_FIELD_NUMBER: builtins.int
        SENSOR_FIELD_NUMBER: builtins.int
        MAGNET_FIELD_NUMBER: builtins.int
        DIPOLE_FIELD_NUMBER: builtins.int
        MAPPING_FIELD_NUMBER: builtins.int
        AXIS_TO_HINGE_BINDINGS_FIELD_NUMBER: builtins.int
        @property
        def joint_frames(self) -> global___JointFrames: ...
        @property
        def sensor(self) -> global___SensorGeometry: ...
        @property
        def magnet(self) -> global___MagnetGeometry: ...
        @property
        def dipole(self) -> global___DipoleSeed: ...
        @property
        def mapping(self) -> global___SensorMapping: ...
        @property
        def axis_to_hinge_bindings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AxisToHingeBindings]: ...
        def __init__(
            self,
            *,
            joint_frames: global___JointFrames | None = ...,
            sensor: global___SensorGeometry | None = ...,
            magnet: global___MagnetGeometry | None = ...,
            dipole: global___DipoleSeed | None = ...,
            mapping: global___SensorMapping | None = ...,
            axis_to_hinge_bindings: collections.abc.Iterable[global___AxisToHingeBindings] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["dipole", b"dipole", "joint_frames", b"joint_frames", "magnet", b"magnet", "mapping", b"mapping", "sensor", b"sensor"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["axis_to_hinge_bindings", b"axis_to_hinge_bindings", "dipole", b"dipole", "joint_frames", b"joint_frames", "magnet", b"magnet", "mapping", b"mapping", "sensor", b"sensor"]) -> None: ...

    @typing.final
    class JointsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___JointModelInfo.JointModel: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___JointModelInfo.JointModel | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    JOINTS_FIELD_NUMBER: builtins.int
    @property
    def joints(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___JointModelInfo.JointModel]: ...
    def __init__(
        self,
        *,
        joints: collections.abc.Mapping[builtins.str, global___JointModelInfo.JointModel] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["joints", b"joints"]) -> None: ...

global___JointModelInfo = JointModelInfo

@typing.final
class TelemetryData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SENSOR_DATA_FIELD_NUMBER: builtins.int
    TIME_SINCE_START_FIELD_NUMBER: builtins.int
    POSE_ESTIMATION_FIELD_NUMBER: builtins.int
    @property
    def sensor_data(self) -> global___SensorData: ...
    @property
    def time_since_start(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def pose_estimation(self) -> global___PoseEstimationData: ...
    def __init__(
        self,
        *,
        sensor_data: global___SensorData | None = ...,
        time_since_start: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        pose_estimation: global___PoseEstimationData | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["pose_estimation", b"pose_estimation", "sensor_data", b"sensor_data", "time_since_start", b"time_since_start"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["pose_estimation", b"pose_estimation", "sensor_data", b"sensor_data", "time_since_start", b"time_since_start"]) -> None: ...

global___TelemetryData = TelemetryData

@typing.final
class Bfield(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BFIELD_FIELD_NUMBER: builtins.int
    @property
    def bfield(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """Bfield vector, pxs: 0, 1, 2, 3, axes: x, y, z, in teslas"""

    def __init__(
        self,
        *,
        bfield: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bfield", b"bfield"]) -> None: ...

global___Bfield = Bfield

@typing.final
class TelemetryDataResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    RESPONSE_DATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> global___TelemetryData: ...
    @property
    def response_data(self) -> clone_client.proto.data_types_pb2.ServerResponse: ...
    def __init__(
        self,
        *,
        data: global___TelemetryData | None = ...,
        response_data: clone_client.proto.data_types_pb2.ServerResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data", "response_data", b"response_data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "response_data", b"response_data"]) -> None: ...

global___TelemetryDataResponse = TelemetryDataResponse

@typing.final
class PressureSensorCalibration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MIN_FIELD_NUMBER: builtins.int
    MAX_FIELD_NUMBER: builtins.int
    min: builtins.int
    max: builtins.int
    def __init__(
        self,
        *,
        min: builtins.int = ...,
        max: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["max", b"max", "min", b"min"]) -> None: ...

global___PressureSensorCalibration = PressureSensorCalibration

@typing.final
class CalibrationData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRESSURE_SENSORS_FIELD_NUMBER: builtins.int
    @property
    def pressure_sensors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PressureSensorCalibration]: ...
    def __init__(
        self,
        *,
        pressure_sensors: collections.abc.Iterable[global___PressureSensorCalibration] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pressure_sensors", b"pressure_sensors"]) -> None: ...

global___CalibrationData = CalibrationData

@typing.final
class Vec3(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    z: builtins.float
    def __init__(
        self,
        *,
        x: builtins.float = ...,
        y: builtins.float = ...,
        z: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["x", b"x", "y", b"y", "z", b"z"]) -> None: ...

global___Vec3 = Vec3

@typing.final
class Joint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Axis(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        AXIS_FIELD_NUMBER: builtins.int
        @property
        def axis(self) -> global___Vec3:
            """1;"""

        def __init__(
            self,
            *,
            axis: global___Vec3 | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_axis", b"_axis", "axis", b"axis"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_axis", b"_axis", "axis", b"axis"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["_axis", b"_axis"]) -> typing.Literal["axis"] | None: ...

    @typing.final
    class AxesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___Joint.Axis: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___Joint.Axis | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    AXES_FIELD_NUMBER: builtins.int
    @property
    def axes(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Joint.Axis]: ...
    def __init__(
        self,
        *,
        axes: collections.abc.Mapping[builtins.str, global___Joint.Axis] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["axes", b"axes"]) -> None: ...

global___Joint = Joint

@typing.final
class JointExt(google.protobuf.message.Message):
    """Joint with information on what nodes are used to estimate it"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOINT_FIELD_NUMBER: builtins.int
    NODE_IDS_FIELD_NUMBER: builtins.int
    @property
    def joint(self) -> global___Joint: ...
    @property
    def node_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        joint: global___Joint | None = ...,
        node_ids: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["joint", b"joint"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["joint", b"joint", "node_ids", b"node_ids"]) -> None: ...

global___JointExt = JointExt

@typing.final
class PoseEstimationInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MagInterpInfo(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class MagMapPosition(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            ANGLES_RAD_FIELD_NUMBER: builtins.int
            BFIELDS_TESLAS_FIELD_NUMBER: builtins.int
            @property
            def angles_rad(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
                """2vec of angles"""

            @property
            def bfields_teslas(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
                """12vec of bfields"""

            def __init__(
                self,
                *,
                angles_rad: collections.abc.Iterable[builtins.float] | None = ...,
                bfields_teslas: collections.abc.Iterable[builtins.float] | None = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["angles_rad", b"angles_rad", "bfields_teslas", b"bfields_teslas"]) -> None: ...

        @typing.final
        class MagMapJointEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            AXIS0NAME_FIELD_NUMBER: builtins.int
            AXIS1NAME_FIELD_NUMBER: builtins.int
            GAUSS_RIDER_ID_FIELD_NUMBER: builtins.int
            ANGLE_BFIELD_POINTS_FIELD_NUMBER: builtins.int
            axis0name: builtins.str
            axis1name: builtins.str
            gauss_rider_id: builtins.int
            """nodeid of corresponding gauss rider"""
            @property
            def angle_bfield_points(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PoseEstimationInfo.MagInterpInfo.MagMapPosition]: ...
            def __init__(
                self,
                *,
                axis0name: builtins.str | None = ...,
                axis1name: builtins.str | None = ...,
                gauss_rider_id: builtins.int = ...,
                angle_bfield_points: collections.abc.Iterable[global___PoseEstimationInfo.MagInterpInfo.MagMapPosition] | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing.Literal["_axis0name", b"_axis0name", "_axis1name", b"_axis1name", "axis0name", b"axis0name", "axis1name", b"axis1name"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing.Literal["_axis0name", b"_axis0name", "_axis1name", b"_axis1name", "angle_bfield_points", b"angle_bfield_points", "axis0name", b"axis0name", "axis1name", b"axis1name", "gauss_rider_id", b"gauss_rider_id"]) -> None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_axis0name", b"_axis0name"]) -> typing.Literal["axis0name"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_axis1name", b"_axis1name"]) -> typing.Literal["axis1name"] | None: ...

        @typing.final
        class MagmapEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> global___PoseEstimationInfo.MagInterpInfo.MagMapJointEntry: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: global___PoseEstimationInfo.MagInterpInfo.MagMapJointEntry | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

        MAGMAP_FIELD_NUMBER: builtins.int
        @property
        def magmap(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___PoseEstimationInfo.MagInterpInfo.MagMapJointEntry]: ...
        def __init__(
            self,
            *,
            magmap: collections.abc.Mapping[builtins.str, global___PoseEstimationInfo.MagInterpInfo.MagMapJointEntry] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["magmap", b"magmap"]) -> None: ...

    @typing.final
    class JointsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___JointExt: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___JointExt | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    JOINTS_FIELD_NUMBER: builtins.int
    MAGINTERP_FIELD_NUMBER: builtins.int
    @property
    def joints(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___JointExt]:
        """1;"""

    @property
    def maginterp(self) -> global___PoseEstimationInfo.MagInterpInfo: ...
    def __init__(
        self,
        *,
        joints: collections.abc.Mapping[builtins.str, global___JointExt] | None = ...,
        maginterp: global___PoseEstimationInfo.MagInterpInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_maginterp", b"_maginterp", "maginterp", b"maginterp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_maginterp", b"_maginterp", "joints", b"joints", "maginterp", b"maginterp"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_maginterp", b"_maginterp"]) -> typing.Literal["maginterp"] | None: ...

global___PoseEstimationInfo = PoseEstimationInfo

@typing.final
class SystemInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MuscleInfo(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        INDEX_FIELD_NUMBER: builtins.int
        NODE_ID_FIELD_NUMBER: builtins.int
        CHANNEL_ID_FIELD_NUMBER: builtins.int
        index: builtins.int
        node_id: builtins.int
        channel_id: builtins.int
        def __init__(
            self,
            *,
            index: builtins.int = ...,
            node_id: builtins.int = ...,
            channel_id: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["channel_id", b"channel_id", "index", b"index", "node_id", b"node_id"]) -> None: ...

    @typing.final
    class MusclesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___SystemInfo.MuscleInfo: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___SystemInfo.MuscleInfo | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    MUSCLES_FIELD_NUMBER: builtins.int
    CALIBRATION_DATA_FIELD_NUMBER: builtins.int
    TELEMETRY_CONFIG_FIELD_NUMBER: builtins.int
    POSE_ESTIMATION_FIELD_NUMBER: builtins.int
    JOINT_MODEL_INFO_FIELD_NUMBER: builtins.int
    telemetry_config: global___TelemetryConfig.ValueType
    @property
    def muscles(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___SystemInfo.MuscleInfo]: ...
    @property
    def calibration_data(self) -> global___CalibrationData:
        """3;"""

    @property
    def pose_estimation(self) -> global___PoseEstimationInfo: ...
    @property
    def joint_model_info(self) -> global___JointModelInfo: ...
    def __init__(
        self,
        *,
        muscles: collections.abc.Mapping[builtins.str, global___SystemInfo.MuscleInfo] | None = ...,
        calibration_data: global___CalibrationData | None = ...,
        telemetry_config: global___TelemetryConfig.ValueType = ...,
        pose_estimation: global___PoseEstimationInfo | None = ...,
        joint_model_info: global___JointModelInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_joint_model_info", b"_joint_model_info", "_pose_estimation", b"_pose_estimation", "calibration_data", b"calibration_data", "joint_model_info", b"joint_model_info", "pose_estimation", b"pose_estimation"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_joint_model_info", b"_joint_model_info", "_pose_estimation", b"_pose_estimation", "calibration_data", b"calibration_data", "joint_model_info", b"joint_model_info", "muscles", b"muscles", "pose_estimation", b"pose_estimation", "telemetry_config", b"telemetry_config"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_joint_model_info", b"_joint_model_info"]) -> typing.Literal["joint_model_info"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_pose_estimation", b"_pose_estimation"]) -> typing.Literal["pose_estimation"] | None: ...

global___SystemInfo = SystemInfo

@typing.final
class SystemInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INFO_FIELD_NUMBER: builtins.int
    RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def info(self) -> global___SystemInfo: ...
    @property
    def response(self) -> clone_client.proto.data_types_pb2.ServerResponse: ...
    def __init__(
        self,
        *,
        info: global___SystemInfo | None = ...,
        response: clone_client.proto.data_types_pb2.ServerResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["info", b"info", "response", b"response"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["info", b"info", "response", b"response"]) -> None: ...

global___SystemInfoResponse = SystemInfoResponse
