"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import clone_client.proto.data_types_pb2
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _TelemetryConfig:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TelemetryConfigEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TelemetryConfig.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PRESSURE: _TelemetryConfig.ValueType  # 0
    IMU: _TelemetryConfig.ValueType  # 1
    ALL: _TelemetryConfig.ValueType  # 2

class TelemetryConfig(_TelemetryConfig, metaclass=_TelemetryConfigEnumTypeWrapper): ...

PRESSURE: TelemetryConfig.ValueType  # 0
IMU: TelemetryConfig.ValueType  # 1
ALL: TelemetryConfig.ValueType  # 2
global___TelemetryConfig = TelemetryConfig

class _JointType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _JointTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_JointType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DOF1: _JointType.ValueType  # 0
    DOF3: _JointType.ValueType  # 1

class JointType(_JointType, metaclass=_JointTypeEnumTypeWrapper): ...

DOF1: JointType.ValueType  # 0
DOF3: JointType.ValueType  # 1
global___JointType = JointType

@typing.final
class PoseVectorResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QPOS_FIELD_NUMBER: builtins.int
    RESPONSE_DATA_FIELD_NUMBER: builtins.int
    @property
    def qpos(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def response_data(self) -> clone_client.proto.data_types_pb2.ServerResponse: ...
    def __init__(
        self,
        *,
        qpos: collections.abc.Iterable[builtins.float] | None = ...,
        response_data: clone_client.proto.data_types_pb2.ServerResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["response_data", b"response_data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["qpos", b"qpos", "response_data", b"response_data"]) -> None: ...

global___PoseVectorResponse = PoseVectorResponse

@typing.final
class IMUData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: builtins.int
    W_FIELD_NUMBER: builtins.int
    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    AX_FIELD_NUMBER: builtins.int
    AY_FIELD_NUMBER: builtins.int
    AZ_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    w: builtins.float
    x: builtins.float
    y: builtins.float
    z: builtins.float
    ax: builtins.float
    ay: builtins.float
    az: builtins.float
    def __init__(
        self,
        *,
        node_id: builtins.int = ...,
        w: builtins.float = ...,
        x: builtins.float = ...,
        y: builtins.float = ...,
        z: builtins.float = ...,
        ax: builtins.float = ...,
        ay: builtins.float = ...,
        az: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ax", b"ax", "ay", b"ay", "az", b"az", "node_id", b"node_id", "w", b"w", "x", b"x", "y", b"y", "z", b"z"]) -> None: ...

global___IMUData = IMUData

@typing.final
class MagneticSensor(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MagneticPixel(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        X_FIELD_NUMBER: builtins.int
        Y_FIELD_NUMBER: builtins.int
        Z_FIELD_NUMBER: builtins.int
        x: builtins.int
        y: builtins.int
        z: builtins.int
        def __init__(
            self,
            *,
            x: builtins.int = ...,
            y: builtins.int = ...,
            z: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["x", b"x", "y", b"y", "z", b"z"]) -> None: ...

    PIXELS_FIELD_NUMBER: builtins.int
    TEMPERATURE_FIELD_NUMBER: builtins.int
    temperature: builtins.int
    @property
    def pixels(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MagneticSensor.MagneticPixel]: ...
    def __init__(
        self,
        *,
        pixels: collections.abc.Iterable[global___MagneticSensor.MagneticPixel] | None = ...,
        temperature: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pixels", b"pixels", "temperature", b"temperature"]) -> None: ...

global___MagneticSensor = MagneticSensor

@typing.final
class MagneticHubRaw(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: builtins.int
    SENSORS_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    @property
    def sensors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MagneticSensor]: ...
    def __init__(
        self,
        *,
        node_id: builtins.int = ...,
        sensors: collections.abc.Iterable[global___MagneticSensor] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["node_id", b"node_id", "sensors", b"sensors"]) -> None: ...

global___MagneticHubRaw = MagneticHubRaw

@typing.final
class GaussRiderRaw(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: builtins.int
    SENSOR_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    @property
    def sensor(self) -> global___MagneticSensor: ...
    def __init__(
        self,
        *,
        node_id: builtins.int = ...,
        sensor: global___MagneticSensor | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["sensor", b"sensor"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["node_id", b"node_id", "sensor", b"sensor"]) -> None: ...

global___GaussRiderRaw = GaussRiderRaw

@typing.final
class TelemetryData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRESSURES_FIELD_NUMBER: builtins.int
    ROT_FIELD_NUMBER: builtins.int
    MAGNETIC_DATA_FIELD_NUMBER: builtins.int
    GAUSS_RIDER_DATA_FIELD_NUMBER: builtins.int
    @property
    def pressures(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def rot(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IMUData]: ...
    @property
    def magnetic_data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MagneticHubRaw]:
        """Unprocessed magnetic hub's data - currently also here"""

    @property
    def gauss_rider_data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GaussRiderRaw]:
        """Unprocessed gauss rider's data"""

    def __init__(
        self,
        *,
        pressures: collections.abc.Iterable[builtins.float] | None = ...,
        rot: collections.abc.Iterable[global___IMUData] | None = ...,
        magnetic_data: collections.abc.Iterable[global___MagneticHubRaw] | None = ...,
        gauss_rider_data: collections.abc.Iterable[global___GaussRiderRaw] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["gauss_rider_data", b"gauss_rider_data", "magnetic_data", b"magnetic_data", "pressures", b"pressures", "rot", b"rot"]) -> None: ...

global___TelemetryData = TelemetryData

@typing.final
class TelemetryDataResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    RESPONSE_DATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> global___TelemetryData: ...
    @property
    def response_data(self) -> clone_client.proto.data_types_pb2.ServerResponse: ...
    def __init__(
        self,
        *,
        data: global___TelemetryData | None = ...,
        response_data: clone_client.proto.data_types_pb2.ServerResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data", "response_data", b"response_data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "response_data", b"response_data"]) -> None: ...

global___TelemetryDataResponse = TelemetryDataResponse

@typing.final
class PressureSensorCalibration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MIN_FIELD_NUMBER: builtins.int
    MAX_FIELD_NUMBER: builtins.int
    min: builtins.int
    max: builtins.int
    def __init__(
        self,
        *,
        min: builtins.int = ...,
        max: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["max", b"max", "min", b"min"]) -> None: ...

global___PressureSensorCalibration = PressureSensorCalibration

@typing.final
class CalibrationData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRESSURE_SENSORS_FIELD_NUMBER: builtins.int
    @property
    def pressure_sensors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PressureSensorCalibration]: ...
    def __init__(
        self,
        *,
        pressure_sensors: collections.abc.Iterable[global___PressureSensorCalibration] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pressure_sensors", b"pressure_sensors"]) -> None: ...

global___CalibrationData = CalibrationData

@typing.final
class ImuMappingModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    PARENT_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    name: builtins.str
    parent: builtins.int
    def __init__(
        self,
        *,
        node_id: builtins.int = ...,
        name: builtins.str = ...,
        parent: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "node_id", b"node_id", "parent", b"parent"]) -> None: ...

global___ImuMappingModel = ImuMappingModel

@typing.final
class Quaternion(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    W_FIELD_NUMBER: builtins.int
    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    w: builtins.float
    x: builtins.float
    y: builtins.float
    z: builtins.float
    def __init__(
        self,
        *,
        w: builtins.float = ...,
        x: builtins.float = ...,
        y: builtins.float = ...,
        z: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["w", b"w", "x", b"x", "y", b"y", "z", b"z"]) -> None: ...

global___Quaternion = Quaternion

@typing.final
class Joint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    BONE_CHILD_FIELD_NUMBER: builtins.int
    BONE_PARENT_FIELD_NUMBER: builtins.int
    JTYPE_FIELD_NUMBER: builtins.int
    IMU_ID_CHILD_FIELD_NUMBER: builtins.int
    IMU_ID_PARENT_FIELD_NUMBER: builtins.int
    R_IMU2JNT_CHILD_FIELD_NUMBER: builtins.int
    R_IMU2JNT_PARENT_FIELD_NUMBER: builtins.int
    QPOS_NR_FIELD_NUMBER: builtins.int
    JNT_NR_FIELD_NUMBER: builtins.int
    name: builtins.str
    bone_child: builtins.str
    bone_parent: builtins.str
    jtype: global___JointType.ValueType
    imu_id_child: builtins.int
    imu_id_parent: builtins.int
    qpos_nr: builtins.int
    jnt_nr: builtins.int
    @property
    def r_imu2jnt_child(self) -> global___Quaternion: ...
    @property
    def r_imu2jnt_parent(self) -> global___Quaternion: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        bone_child: builtins.str = ...,
        bone_parent: builtins.str = ...,
        jtype: global___JointType.ValueType = ...,
        imu_id_child: builtins.int = ...,
        imu_id_parent: builtins.int = ...,
        r_imu2jnt_child: global___Quaternion | None = ...,
        r_imu2jnt_parent: global___Quaternion | None = ...,
        qpos_nr: builtins.int = ...,
        jnt_nr: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["r_imu2jnt_child", b"r_imu2jnt_child", "r_imu2jnt_parent", b"r_imu2jnt_parent"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bone_child", b"bone_child", "bone_parent", b"bone_parent", "imu_id_child", b"imu_id_child", "imu_id_parent", b"imu_id_parent", "jnt_nr", b"jnt_nr", "jtype", b"jtype", "name", b"name", "qpos_nr", b"qpos_nr", "r_imu2jnt_child", b"r_imu2jnt_child", "r_imu2jnt_parent", b"r_imu2jnt_parent"]) -> None: ...

global___Joint = Joint

@typing.final
class SystemInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MuscleInfo(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        INDEX_FIELD_NUMBER: builtins.int
        NODE_ID_FIELD_NUMBER: builtins.int
        CHANNEL_ID_FIELD_NUMBER: builtins.int
        index: builtins.int
        node_id: builtins.int
        channel_id: builtins.int
        def __init__(
            self,
            *,
            index: builtins.int = ...,
            node_id: builtins.int = ...,
            channel_id: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["channel_id", b"channel_id", "index", b"index", "node_id", b"node_id"]) -> None: ...

    @typing.final
    class MusclesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___SystemInfo.MuscleInfo: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___SystemInfo.MuscleInfo | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    MUSCLES_FIELD_NUMBER: builtins.int
    CALIBRATION_DATA_FIELD_NUMBER: builtins.int
    TELEMETRY_CONFIG_FIELD_NUMBER: builtins.int
    JOINTS_FIELD_NUMBER: builtins.int
    telemetry_config: global___TelemetryConfig.ValueType
    @property
    def muscles(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___SystemInfo.MuscleInfo]: ...
    @property
    def calibration_data(self) -> global___CalibrationData:
        """repeated ImuMappingModel imus=3;"""

    @property
    def joints(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Joint]: ...
    def __init__(
        self,
        *,
        muscles: collections.abc.Mapping[builtins.str, global___SystemInfo.MuscleInfo] | None = ...,
        calibration_data: global___CalibrationData | None = ...,
        telemetry_config: global___TelemetryConfig.ValueType = ...,
        joints: collections.abc.Iterable[global___Joint] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["calibration_data", b"calibration_data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["calibration_data", b"calibration_data", "joints", b"joints", "muscles", b"muscles", "telemetry_config", b"telemetry_config"]) -> None: ...

global___SystemInfo = SystemInfo

@typing.final
class SystemInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INFO_FIELD_NUMBER: builtins.int
    RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def info(self) -> global___SystemInfo: ...
    @property
    def response(self) -> clone_client.proto.data_types_pb2.ServerResponse: ...
    def __init__(
        self,
        *,
        info: global___SystemInfo | None = ...,
        response: clone_client.proto.data_types_pb2.ServerResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["info", b"info", "response", b"response"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["info", b"info", "response", b"response"]) -> None: ...

global___SystemInfoResponse = SystemInfoResponse
